### ISSUE TITLE
elastic connector-A TOKEN must be set error

### ISSUE THREAD

**Issue by Nouraufh** [OpenCTI-Platform/connectors#1059]
hello 
 i am trying to integrate elastic 7.16.3 with openCTI  
 i used latest connector and i downloaded reference-config.yml and modified the configuration and followed the steps 

i got the following error

Traceback (most recent call last):
  File "/runtime/bin/elastic", line 8, in <module>
    sys.exit(main())
  File "/runtime/lib/python3.9/site-packages/elastic/console.py", line 225, in main
    ElasticInstance = ElasticConnector(config=config, datadir=datadir)
  File "/runtime/lib/python3.9/site-packages/elastic/elastic.py", line 25, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/runtime/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 590, in __init__
    self.api = OpenCTIApiClient(
  File "/runtime/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 125, in __init__
    raise ValueError("A TOKEN must be set")
ValueError: A TOKEN must be set

**Comment by SamuelHassine** [comment]
Hello,

It seems you did not configure your connector with a proper OpenCTI token.

Kind regards,
Samuel

**Comment by romain-filigran** [comment]
Closing this issue as it has been open for a long time and the problem appears to have been resolved in the meantime (likely fixed by a more recent release or a related change).

If you are still experiencing this issue on the latest version, please feel free to reopen it or create a new one with updated reproduction steps and environment details.

Thank you! 🙏
