### ISSUE TITLE
OTX Connector 504 

### ISSUE THREAD

**Issue by izm1chael** [OpenCTI-Platform/connectors#1060]
## Description
Unable to pull OTX pulses as it will consistently time out, 

This has happened on the 2 most recent versions,

## Environment

1. OS: Ubuntu 22.04
2. OpenCTI version: 5.6.2
3. OpenCTI client: Frontend
4. Other environment details: Docker

## Expected Output

Download OTX pulses into OpenCTI

## Actual Output
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 178, in get
    response = self.session().get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2023-03-03T16%3A00%3A00 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 8, in <module>
    connector.run()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 255, in run
    pulse_import_state = self.pulse_importer.run(current_state, work_id)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 100, in run
    pulses = self._fetch_subscribed_pulses(latest_pulse_datetime)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 191, in _fetch_subscribed_pulses
    pulses = self.client.get_pulses_subscribed(modified_since)
  File "/opt/opencti-connector-alienvault/alienvault/client.py", line 40, in get_pulses_subscribed
    pulse_data = self.otx.getsince(timestamp=modified_since, limit=limit)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 431, in getsince
    return self.getall(limit=limit, modified_since=timestamp, max_page=max_page, max_items=max_items, iter=False)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 404, in getall
    return self.walkapi(
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 385, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page, max_items=max_items, method=method, body=body))
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 366, in walkapi_iter
    data = self.get(next_page_url)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 187, in get
    raise RetryError()
OTXv2.RetryError: 'Exceeded maximum number of retries'
```

**Comment by SamuelHassine** [comment]
Hello,

It seems it is linked to a problem of connectivity from your environment to otx.alienvault.com and not linked to OpenCTI.

Kind regards,
Samuel
