### ISSUE TITLE
Cannot read property 'map' of null","locations":[{"line":4,"column":25}],"path":["reportEdit","relationAdd"],

### ISSUE THREAD

**Issue by phucsnguyenv** [OpenCTI-Platform/connectors#141]
## Description

Error while adding observables to a report

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.4
2. OpenCTI version: 3.2.2
3. OpenCTI client: pycti `3.2.3`

## Reproducible Steps
I am trying to execute this code to and an observable to a report 
```python
        for created_observable_stix_id in created_observable_id_list:
            self.helper.log_info("Attaching {} to report -- {}".format(created_observable_stix_id, type(created_observable_stix_id)))
            self.helper.api.report.add_stix_observable(
                id=created_report["id"], stix_observable_id=created_observable_stix_id,report=created_report
            )
```
But I got the following error
```
connector-internal-import_1  | ERROR:root:An unknown error has occurred!  Please try again later.
```

I try to use `graphql` on web client. The query I use is copied from the `pycti` library
```json
mutation ReportEdit($id: ID!, $input: RelationAddInput) {
                   reportEdit(id: $id) {
                        relationAdd(input: $input) {
                            id
                        }
                   }
               },
{
  "id": "97530ca-2ef9-4d4c-ac48-10b7ebd0c93c",
                      "input": {
                        "fromRole": "observables_aggregation",
                        "toId": "observable--05e2eefe-4d05-4990-a286-398a2d41c2ea",
                        "toRole": "soo",
                        "through": "observable_refs",
                    },
}
```
And here is actual output
```json
{
  "error": {
    "errors": [
      {
        "message": "An unknown error has occurred!  Please try again later.",
        "name": "Unknown",
        "time_thrown": "2020-05-15T02:08:51.951Z",
        "data": {
          "type": "technical",
          "level": "error"
        }
      }
    ]
  }
}
```

## Log from OpenCTI

```
connector-internal-import_1  | INFO:root:Adding Stix-Observable {observable--7a3057ac-8710-4000-9d4a-66b0c7afd1b0} to Report {f97530ca-2ef9-4d4c-ac48-10b7ebd0c93c}
opencti_1                    | {"error":{},"level":"error","message":"[GRAKN] executeWrite error"}
opencti_1                    | {"error":{"message":"Cannot read property 'map' of null","locations":[{"line":4,"column":25}],"path":["reportEdit","relationAdd"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'map' of null","    at /opt/opencti/build/index.js:1:27014","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)","    at async L (/opt/opencti/build/index.js:1:4607)","    at async Ie (/opt/opencti/build/index.js:1:26538)","    at async Ce (/opt/opencti/build/index.js:1:29702)","    at async x (/opt/opencti/build/index.js:1:60604)"]}}},"level":"error","message":"[OPENCTI] Technical error"}
connector-internal-import_1  | ERROR:root:An unknown error has occurred!  Please try again later.
```

**Comment by SamuelHassine** [comment]
Hello @phucsnguyenv, please use the stix_observable OpenCTI ID in `stix_observable_id=created_observable_stix_id`and not the STIX ID. For the moment, in all OpenCTI "relation" related method, only the OpenCTI ID is supported. We intend to change that and to support both STIX ID and OpenCTI.

**Comment by phucsnguyenv** [comment]
Hi @SamuelHassine 

Thanks for reverting... 
I see the problem in the code.. I will fix it...
anw, I would like to contribute the connector which I have done, can I?

**Comment by SamuelHassine** [comment]
Yes please contribute!
