### ISSUE TITLE
Feedly Connector Error

### ISSUE THREAD

**Issue by MaxK-Altus** [OpenCTI-Platform/connectors#1504]
## Description

Hey guys,

I have an error with the Feedly connector (5.11.5), running with docker compose. What am I doing wrong? 

```
ERROR Variable "$input" got invalid value { id: "a0eab1c1-3f48-4ba7-9444-07c184eb2bfa", name: "Feedly", type: "EXTERNAL_IMPORT", scope: ["feedly"], auto: false, only_contextual: false, playbook_compatible: false }; Field "playbook_compatible" is not defined by type "RegisterConnectorInput". | timestamp=2023-10-24T17:25:18.294862Z name=pycti.api

Traceback (most recent call last):

  File "/opt/opencti-feedly-connector/main.py", line 28, in <module>

    _helper = load_helper()

              ^^^^^^^^^^^^^

  File "/opt/opencti-feedly-connector/main.py", line 22, in load_helper

    raise e

  File "/opt/opencti-feedly-connector/main.py", line 19, in load_helper

    return OpenCTIConnectorHelper(config)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 686, in __init__

    connector_configuration = self.api.connector.register(self.connector)

                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_connector.py", line 103, in register

    result = self.api.query(query, connector.to_input())

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 365, in query

    raise ValueError(

ValueError: {'name': 'Variable "$input" got invalid value { id: "a0eab1c1-3f48-4ba7-9444-07c184eb2bfa", name: "Feedly", type: "EXTERNAL_IMPORT", scope: ["feedly"], auto: false, only_contextual: false, playbook_compatible: false }; Field "playbook_compatible" is not defined by type "RegisterConnectorInput".', 'message': 'Variable "$input" got invalid value { id: "a0eab1c1-3f48-4ba7-9444-07c184eb2bfa", name: "Feedly", type: "EXTERNAL_IMPORT", scope: ["feedly"], auto: false, only_contextual: false, playbook_compatible: false }; Field "playbook_compatible" is not defined by type "RegisterConnectorInput".'}

Terminated
```

## Environment

1. OS Ubuntu 22.04.3 LTS 
2. OpenCTI version: 5.10.2
3. OpenCTI client: 
4. Docker Compose version v2.21.0 | connector-feedly:5.11.5

## Reproducible Steps

Run Feedly connector with the following docker compose. 

```
connector-feedly:
    image: opencti/connector-feedly:5.11.5
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=UUID-4-removed-for-security-reasons
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=Feedly
      - CONNECTOR_SCOPE=feedly # MIME type or Stix Object
      - CONNECTOR_CONFIDENCE_LEVEL=4 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=error
      - FEEDLY_INTERVAL=60 # in minutes
      - FEEDLY_STREAM_IDS=enterprise/COMPANY-NAME/category/ID-removed-for-security-reasons # Comma separated list of stream ids
      - FEEDLY_DAYS_TO_BACK_FILL=7 # Number of days to back fill for new stream ids
      - FEEDLY_API_KEY=fe_removed-for-security-reasons
    restart: always
    depends_on:
      - opencti
```

## Additional information

No additional information

**Comment by MaxK-Altus** [comment]
Fixed by updating and arranging OpenCTI and Feedly connector to version 5.11.11
