### ISSUE TITLE
[MalwareBazaar Recent Additions] [URLhaus Recent Payloads] ERROR Cannot query field "edges" on type "Label"

### ISSUE THREAD

**Issue by dominictory** [OpenCTI-Platform/connectors#1794]
## Description

Malware Bazaar Recent Additions connector does not function.

`ERROR {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'} | timestamp=2024-02-06T09:40:21.196150Z name=MalwareBazaar Recent Additions exc_info=Traceback (most recent call last):
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 128, in run
    response = self.upload_artifact_opencti(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-malwarebazaar-recent-additions/malwarebazaar-recent-additions.py", line 260, in upload_artifact_opencti
    return self.helper.api.stix_cyber_observable.upload_artifact(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1736, in upload_artifact
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 344, in query
    raise ValueError(
ValueError: {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'}`

## Environment

5.12.25

**Comment by dominictory** [comment]
Same issue with URLHaus Recent Payloads:

`ERROR {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'} | timestamp=2024-02-06T12:11:43.846657Z name=URLhaus Recent Payloads exc_info=Traceback (most recent call last):
  File "/opt/opencti-connector-urlhaus-recent-payloads/urlhaus-recent-payloads.py", line 179, in run
    response = self.upload_artifact_opencti(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-urlhaus-recent-payloads/urlhaus-recent-payloads.py", line 316, in upload_artifact_opencti
    return self.helper.api.stix_cyber_observable.upload_artifact(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/entities/opencti_stix_cyber_observable.py", line 1736, in upload_artifact
    result = self.opencti.query(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 344, in query
    raise ValueError(
ValueError: {'name': 'Cannot query field "edges" on type "Label".', 'message': 'Cannot query field "edges" on type "Label".'}

'str' object cannot be interpreted as an integer`

**Comment by dominictory** [comment]
Resolved by updating to 5.12.28.
