### ISSUE TITLE
[OpenCTI Dataset] Organizations dataset no longer works and returns errors

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#1908]
## Description

Organizations are no longer imported by the OpenCTI dataset connector and errors occur

## Environment

OCTI 6.0.5

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run the OpenCTI dataset connector
2. Check its work, you will see lots of errors (see screenshot)

## Screenshots

![Screenshot 2024-03-10 040707](https://github.com/OpenCTI-Platform/connectors/assets/70956706/cf8987c6-a093-4de9-abfc-fcb6ccb1155d)

**Comment by Jipegien** [comment]
After identifying the root cause, assess if the other datasets (sectors, etc.) are impacted.

**Comment by Jipegien** [comment]
@helene-nguyen do you have some ETA on this?

**Comment by helene-nguyen** [comment]
@Jipegien, @Lhorus6, after some investigations, the connector send properly the data and the error is raised from the worker while ingesting data.

We need to check the data sent itself, there are no recent changes in the worker code base.

The following error is raised when trying to handle vocab:

```
INFO:api:Creating or Getting aliased Vocabulary
ERROR:worker:'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\helen\IdeaProjects\opencti\opencti-worker\src\worker.py", line 268, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 215, in import_bundle_from_json
    return self.import_bundle(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 2456, in import_bundle
    self.import_object(item, update, types)
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 854, in import_object
    embedded_relationships = self.extract_embedded_relationships(stix_object, types)
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 349, in extract_embedded_relationships
    self.opencti.vocabulary.handle_vocab(
TypeError: 'NoneType' object is not subscriptable
```
And this while creating STIX core relationship:

```
INFO:api:Creating stix_core_relationship
WARNING:worker:Traceback (most recent call last):
  File "C:\Users\helen\IdeaProjects\opencti\opencti-worker\src\worker.py", line 268, in data_handler
    self.api.stix2.import_bundle_from_json(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 215, in import_bundle_from_json
    return self.import_bundle(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 2357, in import_bundle
    self.import_relationship(item, update, types)
  File "C:\Users\helen\IdeaProjects\client-python\pycti\utils\opencti_stix2.py", line 1223, in import_relationship
    stix_relation_result = self.opencti.stix_core_relationship.import_from_stix2(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\entities\opencti_stix_core_relationship.py", line 1132, in import_from_stix2
    return self.create(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\entities\opencti_stix_core_relationship.py", line 611, in create
    result = self.opencti.query(
  File "C:\Users\helen\IdeaProjects\client-python\pycti\api\opencti_api_client.py", line 351, in query
    raise ValueError(
ValueError: {'name': 'MISSING_REFERENCE_ERROR', 'message': 'Element(s) not found'}
```

Knowing that, do you have informations about recent changes that have been made concerning vocabulary or relationships ?

**Comment by Jipegien** [comment]
@helene-nguyen there was some changes on open vocab regarding Organization type, handled by @frapuks. I don't recall anything about relationship modifications..

**Comment by SamuelHassine** [comment]
@Jipegien @helene-nguyen I've fixed this in the Python library: https://github.com/OpenCTI-Platform/client-python/commit/6a3fd7c613f509e52b57712daae04c8de9120f24
