### ISSUE TITLE
Crowdsec connector seems to be lacking a depedency

### ISSUE THREAD

**Issue by troll-os** [OpenCTI-Platform/connectors#1946]
## Description

When running the Crowdsec connector in our envs, the connector fails to start with the stack trace given below

## Environment

Filigran

## Reproducible Steps

Run the Crowdsec connector, no special configs applied

## Expected Output

Connector is alive

## Actual Output

```
Traceback (most recent call last):
  File "/opt/opencti-crowdsec/crowdsec.py", line 11, in <module>
    from pycti import OpenCTIConnectorHelper, get_config_variable
  File "/usr/local/lib/python3.11/site-packages/pycti/__init__.py", line 4, in <module>
    from .api.opencti_api_client import OpenCTIApiClient
  File "/usr/local/lib/python3.11/site-packages/pycti/api/opencti_api_client.py", line 8, in <module>
    import magic
  File "/usr/local/lib/python3.11/site-packages/magic/__init__.py", line 209, in <module>
    libmagic = loader.load_lib()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/magic/loader.py", line 49, in load_lib
    raise ImportError('failed to find libmagic.  Check your installation')
```

**Comment by nino-filigran** [comment]
@sbs2001 I see that you have created the connector at first. Would you mind having a look if you can?

**Comment by rr404** [comment]
Pushed a fix:  https://github.com/OpenCTI-Platform/connectors/pull/1953

I indeed had the same error as you @troll-os when I tried a fresh install. the changes in the PR fix the issue
