### ISSUE TITLE
Backup Files Connector Terminates

### ISSUE THREAD

**Issue by explorecti** [OpenCTI-Platform/connectors#1979]
## Description

Connector Backup Files fails to connect (terminates).

## Environment

1. OS: Ubuntu 20.04.6
2. OpenCTI version: 6.0.8
3. OpenCTI client: Frontend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create the connector in a docker compose stack
connector-backup-files:
    image: opencti/connector-backup-files:6.0.8
    environment:
      - OPENCTI_URL=https://opencti:8443 # Local OpenCTI URL
      - OPENCTI_TOKEN=UUID # Local OpenCTI token
      - CONNECTOR_ID=UUID
      - CONNECTOR_LIVE_STREAM_ID=live # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      - CONNECTOR_NAME=BackupFiles
      - CONNECTOR_SCOPE=backup
      - CONNECTOR_LOG_LEVEL=error
      - BACKUP_PROTOCOL=local # Protocol for file copy (only `local` is supported for now).
      - BACKUP_PATH=/tmp # Path to be used to copy the data, can be relative or absolute.
    restart: always

## Expected Output

On the local server file system running the platform a directory (opencti_data, full path /tmp/opencti_data) should be created and backup files placed.

## Actual Output

HTTPS request is being made to host 'opencti'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
2024-03-25T14:56:58.163550051Z   warnings.warn(
2024-03-25T14:56:58.216439985Z /usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py:1103: InsecureRequestWarning: Unverified HTTPS request is being made to host 'opencti'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
2024-03-25T14:56:58.216483060Z   warnings.warn(
2024-03-25T14:56:58.261879975Z ERROR Error in ListenStream loop, exit. | timestamp=2024-03-25T14:56:58.261556Z name=BackupFiles exc_info=Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.11/ssl.py", line 1382, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /stream/live?recover=2024-03-25T14:56:58Z (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 602, in run
    messages = SSEClient(
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/filigran_sseclient/sseclient.py", line 50, in __init__
    self._connect()
  File "/usr/local/lib/python3.11/site-packages/filigran_sseclient/sseclient.py", line 58, in _connect
    self.resp = requester.get(self.url, stream=True, **self.requests_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /stream/live?recover=2024-03-25T14:56:58Z (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) attributes={"reason":"HTTPSConnectionPool(host='opencti', port=8443): Max retries exceeded with url: /stream/live?recover=2024-03-25T14:56:58Z (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"}
2024-03-25T14:56:58.265717410Z Terminated

## Additional information

None

**Comment by pierremahot** [comment]
Hello @explorecti ,
This connector does not support the environment variable `BACKUP_SSL_VERIFY=false`.
If it is possible not to use https for your docker compose (if it is on the same machine https is not really relevant) you can use http to connect to the opencti platform inside the docker compose network.
`- OPENCTI_URL=http://opencti:8080`
If you really want full https, you will need to add the certificate inside the container before running the script.
Another solution might be to set the `REQUESTS_CA_BUNDLE` environment variable to `""` so that the urllib3 python lib doesn't do the verification as described here https://stackoverflow.com/questions/48391750/disable-python-requests-ssl-validation-for-an-imported-module

**Comment by explorecti** [comment]
Hello @pierremahot,
The connector needs additional features added to allow for https auth. Using the platform running 8080 is not acceptable for my applications and I'm sure for many other users. In addition the REQUEST_CA_BUNDLE is not a working option for the connector currently. Please provide a reasonable resolution or add a variable to the existing code to allow for HTTPS_CERT and HTTPS_KEY. An example of this would be the opencti platform APP_HTTPS_CERT__CRT. Thank you

**Comment by explorecti** [comment]
Is there an update when this connector will be fixed to use HTTPS? This connector use to work many versions back, but noticed the SSL python package was removed.

**Comment by Jipegien** [comment]
No ETA as it is not a priority currently. You can of course submit a PR in the meantime.
