### ISSUE TITLE
Error: Cant upsert entity. Too many entities resolved

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#217]
OpenCTI Platform + Workers: 4.0.3
Malpedia Connector: 4.0.3

Malpedia connector log
```
2020-12-22T21:54:22.995918936Z INFO:root:Creating Intrusion-Set {Dropping Elephant}.
2020-12-22T21:54:23.048887178Z ERROR:root:Cant upsert entity. Too many entities resolved,
2020-12-22T21:54:23.048947204Z ERROR:root:{'name': 'UnsupportedError', 'message': 'Cant upsert entity. Too many entities resolved'},
```

malpedia platform log:
```

{"user":{"ip":"::ffff:172.17.0.1","user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"},"type":"WRITE_ERROR","operation_query":"mutation IntrusionSetAdd($input:IntrusionSetAddInput){intrusionSetAdd(input:$input){id standard_id entity_type parent_types}}","inner_relation_creation":1,"operation":"IntrusionSetAdd","time":20,"variables":{"input":{"stix_id":null,"createdBy":"df3bf72d-135f-4dfa-bb5a-952befde7bdc","objectMarking":null,"objectLabel":null,"externalReferences":null,"revoked":null,"confidence":null,"lang":null,"created":null,"modified":null,"name":"Dropping Elephant","description":"Dropping Elephant (also known as “Chinastrats” and “Patchwork“) is a relatively new threat actor that is targeting a variety of high profile diplomatic and economic targets using a custom set of attack tools. Its victims are all involved with China’s foreign relations in some way, and are generally caught through spear-phishing or watering hole attacks.","aliases":["Chinastrats","Patchwork","Monsoon","Sarit","Quilted Tiger","APT-C-09","ZINC EMERSON"],"first_seen":null,"last_seen":null,"goals":null,"resource_level":null,"primary_motivation":null,"secondary_motivations":null,"update":true}},"size":865,"error":{"data":{"reason":"Cant upsert entity. Too many entities resolved","category":"business","input":{"stix_id":null,"name":"Dropping Elephant","description":"Dropping Elephant (also known as “Chinastrats” and “Patchwork“) is a relatively new threat actor that is targeting a variety of high profile diplomatic and economic targets using a custom set of attack tools. Its victims are all involved with China’s foreign relations in some way, and are generally caught through spear-phishing or watering hole attacks.","aliases":["Chinastrats","Patchwork","Monsoon","Sarit","Quilted Tiger","APT-C-09","ZINC EMERSON"],"first_seen":"1970-01-01T00:00:00.000Z","last_seen":"5138-11-16T09:46:40.000Z","goals":null,"resource_level":null,"primary_motivation":null,"secondary_motivations":null,"confidence":null,"revoked":null,"lang":null,"createdBy":{"standard_id":"identity--f739cb63-738d-5390-86b4-c729c752bf72","identity_class":"organization","x_opencti_organization_type":null,"i_created_at_day":"2020-12-22","spec_version":"2.1","parent_types":["Basic-Object","Stix-Object","Stix-Core-Object","Stix-Domain-Object","Identity"],"roles":null,"description":" The primary goal of Malpedia is to provide a resource for rapid identification and actionable context when investigating malware. Openness to curated contributions shall ensure an accountable level of quality in order to foster meaningful and reproducible research.","contact_information":null,"created_at":"2020-12-22T21:44:58.724Z","x_opencti_aliases":null,"revoked":false,"base_type":"ENTITY","updated_at":"2020-12-22T21:44:58.724Z","modified":"2020-12-22T21:44:58.724Z","i_aliases_ids":["aliases--4ffa6563-4b83-5e7c-8402-ddc89aae310f"],"id":"df3bf72d-135f-4dfa-bb5a-952befde7bdc","lang":"en","internal_id":"df3bf72d-135f-4dfa-bb5a-952befde7bdc","x_opencti_reliability":null,"created":"2020-12-22T21:44:58.724Z","i_created_at_month":"2020-12","confidence":0,"i_created_at_year":"2020","entity_type":"Organization","name":"Malpedia","x_opencti_stix_ids":[],"_index":"opencti_stix_domain_objects"},"objectMarking":null,"objectLabel":null,"externalReferences":null,"created":null,"modified":null,"update":true},"entityIds":["intrusion-set--d86a6b21-ab3d-57f2-b180-732ed7fc03c0","intrusion-set--40ad1390-d497-55eb-85db-8afb3548985d"]},"stacktrace":["UnsupportedError: Unsupported element","at t (/opt/opencti/build/index.js:1:55562)","at o (/opt/opencti/build/index.js:1:56245)","at /opt/opencti/build/index.js:1:27516","at runMicrotasks (<anonymous>)","at processTicksAndRejections (internal/process/task_queues.js:93:5)","at async Fe (/opt/opencti/build/index.js:1:26975)","at async /opt/opencti/build/index.js:1:206812"]},"level":"error","message":"API Call","timestamp":"2020-12-22T21:54:23.041Z"}
```

Malpedia connector config (using api key):
```
OPENCTI_URL=
OPENCTI_TOKEN=
CONNECTOR_ID=
CONNECTOR_TYPE=EXTERNAL_IMPORT
CONNECTOR_NAME=Malpedia
CONNECTOR_SCOPE=malpedia
CONNECTOR_CONFIDENCE_LEVEL=3
CONNECTOR_UPDATE_EXISTING_DATA=true
CONNECTOR_LOG_LEVEL=info
MALPEDIA_AUTH_KEY= xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
MALPEDIA_INTERVAL_SEC=86400 
MALPEDIA_IMPORT_INTRUSION_SETS=true
MALPEDIA_IMPORT_YARA=true
MALPEDIA_CREATE_INDICATORS=true
MALPEDIA_CREATE_OBSERVABLES=true
```

The malpedia connector seems to be generating all the work related logs and doesn't resume after hitting the `UnsupportedError`

**Comment by SamuelHassine** [comment]
Hello @kudrew,

 This is an expected behavior since the version 4, the problem is located at:

![image](https://user-images.githubusercontent.com/1334279/102939651-f0ce9200-44ae-11eb-992c-00703dd91995.png)

Please check in your OpenCTI platform, you has 2 different Intrusion Sets corresponding to this set of name/aliases. OpenCTI is therefore not able to determinate which Intrusion Set to select and then attach the knowledge.

To fix this, merge your 2 intrusion sets or rework the aliases distribution in your OpenCTI platform to match the Malpedia datasource. If you are not agree with Malpedia information, you can still try to make them change the distribution or the data. 

This new system should help the community to choose a good way to distribute data across your own threat carving but also to ease convergence of different vendors despite the well known hard problem of doing that.

Kind regards,
Samuel

**Comment by kudrew** [comment]
Can there be an option so that the connector can skip over the error? The connector has been paused after the last error

**Comment by cdsouza-cta** [comment]
Hi @SamuelHassine , 
Thanks for the explanation. Couple of questions on this. 
1. So we noticed that specific to malpedia , we don't see error and completed logs showing up on the connecter interface, so this makes it hard for us to actually figure out if an error has occurred (in this case duplicates) since there is no display on the connector
![image](https://user-images.githubusercontent.com/44027296/103015770-02e01d00-450f-11eb-8b27-08b7c52838bd.png)

2. It seems once we see the the `UnsupportedError` the connector itself will not pull more data. Based on what you mentioned that this was because of 2 different intrusion sets corresponding to the same name/aliases,  Is it expected for the connector to stop?

Thank you once again for the detailed explanation, it helps us during debugging. 

Thanks, 
Clinton

**Comment by smclinden** [comment]
Is there information in the error message to determine which intrusion set(s) is/are causing the conflict?
