### ISSUE TITLE
MISP connector not working, getting connection error

### ISSUE THREAD

**Issue by azzarin** [OpenCTI-Platform/connectors#230]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

I have setup OpenCTI and MISP. Im now trying to use the connector for OPENCTI. But it fails.
I did set this up in my lab and there it works just fine. so im kinda lost. also rather new to OpenCTI and MISP for that matter. 

I have SSL verify= False
I do have the correct "URL"
I do have the correct Key

Using pymisp with the key and URL from other python scripts works just fine. 

## Environment

1. OS (where OpenCTI server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenCTI version: {4.0.7 }
3. OpenCTI client: {Python i guess?}
4. Other environment details: Running as Docker on a RHEL server. Lab is Ubuntu. not sure if it actually matters.

## Expected Output

{ Please describe what you expected to happen. }

### **_This is the log from OpenCTIv4_connector-misp_**
INFO:root:Listing Threat-Actors with filters null.,
INFO:root:Connector registered with ID:XXXXXX-XXXX-XXXX-XXXX-XXXXXXX
INFO:root:Starting ping alive thread,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn,
    conn = connection.create_connection(,
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection,
    raise err,
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection,
    sock.connect(sa),
OSError: [Errno 113] Host is unreachable,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen,
    httplib_response = self._make_request(,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request,
    self._validate_conn(conn),
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn,
    conn.connect(),
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect,
    conn = self._new_conn(),
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn,
    raise NewConnectionError(,
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send,
    resp = conn.urlopen(,
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen,
    retries = retries.increment(,
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment,
    raise MaxRetryError(_pool, url, error or ResponseError(cause)),
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.10.1.27', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable')),
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/pymisp/api.py", line 129, in __init__,
    response = self.recommended_pymisp_version,
  File "/usr/local/lib/python3.8/site-packages/pymisp/api.py", line 185, in recommended_pymisp_version,
    response = self._prepare_request('GET', 'servers/getPyMISPVersion.json'),
  File "/usr/local/lib/python3.8/site-packages/pymisp/api.py", line 3134, in _prepare_request,
    return self.__session.send(prepped, timeout=self.timeout, **settings),
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send,
    r = adapter.send(request, **kwargs),
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 516, in send,
    raise ConnectionError(e, request=request),
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='10.10.1.27', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable')),
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "misp.py", line 1272, in <module>,
    mispConnector = Misp(),
  File "misp.py", line 137, in __init__,
    self.misp = ExpandedPyMISP(,
  File "/usr/local/lib/python3.8/site-packages/pymisp/api.py", line 150, in __init__,
    raise PyMISPError(f'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}'),
pymisp.exceptions.PyMISPError: Unable to connect to MISP (https://10.10.1.27). Please make sure the API key and the URL are correct (http/https is required): HTTPSConnectionPool(host='10.10.1.27', port=443): Max retries exceeded with url: /servers/getPyMISPVersion.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable')),

**Comment by SamuelHassine** [comment]
Hello,

I think this error is pretty clear: `'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}'),`

The connector is not able to connect to your MISP instance with the URL you configured:

`urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable,`

Kind regards,
Samuel

**Comment by azzarin** [comment]
> Hello,
> 
> I think this error is pretty clear: `'Unable to connect to MISP ({self.root_url}). Please make sure the API key and the URL are correct (http/https is required): {e}'),`
> 
> The connector is not able to connect to your MISP instance with the URL you configured:
> 
> `urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3379c5e3d0>: Failed to establish a new connection: [Errno 113] Host is unreachable,`
> 
> Kind regards,
> Samuel

Yeah, but i have no clue why. The URL is correct. you can access MISP on that URL. Using that URL on PyMISP also works just fine. I did roll the dice and was hoping perhaps this was known to someone.

**Comment by azzarin** [comment]
I did spin up another server and it works just fine. I know its not recommended to run MISP and CTI on the same server. So i guess there is a reason for that 👍
