### ISSUE TITLE
[CrowdStrike] CrowdStrike connector internal error: a bytes-like object is required, not 'dict'

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2647]
## Description

We have errors on the connectors, starting yesterday at about 11:00. I'll make a note of the timing so you'll know if there's ever been a change around here, it might be related.

The error is as follows:

`Traceback (most recent call last):
  File "/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/core.py", line 314, in run
    importer_state = importer.start(work_id, new_state)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/importer.py", line 42, in start
    return self.run(state)
           ^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/rule/yara_master_importer.py", line 76, in run
    yara_master = self._fetch_yara_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-crowdstrike/crowdstrike_feeds_connector/rule/yara_master_importer.py", line 154, in _fetch_yara_master
    download_converted = BytesIO(download)
                         ^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'dict'`

## Environment

OCTI 6.2.18

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. I would say: Enable the CrowdStrike connector and wait

**Comment by romain-filigran** [comment]
@Megafredo : Could you have a look to this issue ?
