### ISSUE TITLE
[ImportExternalReference] Error importing some pages

### ISSUE THREAD

**Issue by Lhorus6** [OpenCTI-Platform/connectors#2674]
## Description

The Import External Reference connector raises the following error for certain reports:

`Traceback (most recent call last):
  File "/opt/opencti-connector-import-external-reference/import-external-reference.py", line 87, in _process_external_reference
    page.goto(url_to_import)
  File "/usr/local/lib/python3.11/site-packages/playwright/sync_api/_generated.py", line 8843, in goto
    self._sync(
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_page.py", line 524, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_frame.py", line 145, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/playwright/_impl/_connection.py", line 514, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.Error: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.mcafee.com/blogs/internet-security/how-to-maximize-the-latest-mcafee-enhancements-for-peace-of-mind-this-autumn
Call log:
navigating to "https://www.mcafee.com/blogs/internet-security/how-to-maximize-the-latest-mcafee-enhancements-for-peace-of-mind-this-autumn", waiting until "load"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pycti/connector/opencti_connector_helper.py", line 352, in _data_handler
    message = self.callback(event_data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-import-external-reference/import-external-reference.py", line 223, in _process_message
    return self._process_external_reference(external_reference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-import-external-reference/import-external-reference.py", line 119, in _process_external_reference
    raise ValueError(e)
ValueError: Page.goto: net::ERR_HTTP2_PROTOCOL_ERROR at https://www.mcafee.com/blogs/internet-security/how-to-maximize-the-latest-mcafee-enhancements-for-peace-of-mind-this-autumn
Call log:
navigating to "https://www.mcafee.com/blogs/internet-security/how-to-maximize-the-latest-mcafee-enhancements-for-peace-of-mind-this-autumn", waiting until "load"
`

## Environment

OCTI 6.3.2

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create an External Ref with one of these two examples:
    - https://www.mcafee.com/blogs/internet-security/unmasking-ai-and-the-future-of-us-five-takeaways-from-the-oprah-tv-special/
    - https://www.mcafee.com/blogs/internet-security/how-to-maximize-the-latest-mcafee-enhancements-for-peace-of-mind-this-autumn/
2. Run the ImportExternalReference connector

## Expected Output

Get the pdf of the page as usual

## Actual Output

I get this error and the pdf is not generated

**Comment by blauwers** [comment]
Small diagnostic note, the issue with these pages appears to be that they are behind Akamai Bot Manager (ABM).
