### ISSUE TITLE
[OrangeCyberDefense]: Exception observed during import of "content_block"

### ISSUE THREAD

**Issue by romain-filigran** [OpenCTI-Platform/connectors#2940]
## Description

Exceptions observed during import of "worldwatch content_block" data.

**Exception: Error during world watch import: 'items'**

`
Traceback (most recent call last):
  File "/opt/opencti-connector-orange-cyberdefense/orange-cyberdefense.py", line 748, in _import_worldwatch
    content_block_list = self.get_content_block_list(world_watch_date)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/opencti-connector-orange-cyberdefense/orange-cyberdefense.py", line 737, in get_content_block_list
    return response.json()["items"]
           ~~~~~~~~~~~~~~~^^^^^^^^^`

## Environment

1. OpenCTI version: 6.3.10

**Comment by romain-filigran** [comment]
Hello @cert-orangecyberdefense : Could you take a look at the problem above ? Thanks

**Comment by romain-filigran** [comment]
Closing this issue as it has been open for a long time and the problem appears to have been resolved in the meantime (likely fixed by a more recent release or a related change).

If you are still experiencing this issue on the latest version, please feel free to reopen it or create a new one with updated reproduction steps and environment details.

Thank you! 🙏
