### ISSUE TITLE
[ImportFileStix] Connector errors with the import of sample stix1.1.1 files

### ISSUE THREAD

**Issue by kudrew** [OpenCTI-Platform/connectors#313]
On 4.3.4 testing the import of some sample stix1.1.1 files and running into some errors:

[https://raw.githubusercontent.com/STIXProject/schemas/version_1.1.1/samples/STIX_Indicator_Snort.xml](https://raw.githubusercontent.com/STIXProject/schemas/version_1.1.1/samples/STIX_Indicator_Snort.xml)
This sample errors out with:
```
Importing the file https://10.150.4.44/storage/get/import/Report/fd8b363c-e887-40d6-9cf1-2129f0922931/STIX_Indicator_Snort.xml,
 Results produced by the stix2-elevator are not for production purposes.,
 [stix2elevator.options] [201] [WARNING] [2021-03-30 20:14:52,633] Results produced by the stix2-elevator may generate warning messages which should be investigated.,
 [stix2elevator.options] [903] [WARNING] [2021-03-30 20:14:52,634] No valid time position information available in indicator--ad560917-6ede-4abb-a4aa-994568a2abf4, using parent timestamp,
 [stix2elevator.options] [504] [WARNING] [2021-03-30 20:14:52,634] YARA/SNORT/IOC or other patterns are not supported in STIX 2.0. See indicator--ad560917-6ede-4abb-a4aa-994568a2abf4,
 ================================================================================,
 [-] Results for: bundle--0935d61b-69a4-4e64-8c4c-d9ce885f7fcc,
 [X] STIX JSON: Invalid,
     [!] Warning: indicator--ad560917-6ede-4abb-a4aa-994568a2abf4: {214} labels contains a value not in the indicator-label-ov vocabulary.,
     [X] indicator--ad560917-6ede-4abb-a4aa-994568a2abf4: 'pattern' is a required property
```

[https://raw.githubusercontent.com/STIXProject/schemas/version_1.1.1/samples/STIX_Phishing_Indicator.xml](https://raw.githubusercontent.com/STIXProject/schemas/version_1.1.1/samples/STIX_Phishing_Indicator.xml)
This sample errors out with:
```
Error in message processing, reporting error to API,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 123, in _data_handler,
    message = self.callback(json_data["event"]),
  File "import-file-stix.py", line 28, in _process_message,
    file_content = elevate(file_content),
  File "/usr/local/lib/python3.8/site-packages/stix2elevator/__init__.py", line 101, in elevate,
    container = stixmarx.parse(stix_package),
  File "/usr/local/lib/python3.8/site-packages/stixmarx/__init__.py", line 26, in parse,
    stix_package = parser.parse_xml(xml_input, encoding),
  File "/usr/local/lib/python3.8/site-packages/stixmarx/parser.py", line 294, in parse_xml,
    parser = MarkingParser(root=xml_input, encoding=encoding),
  File "/usr/local/lib/python3.8/site-packages/stixmarx/parser.py", line 78, in __init__,
    self._root = xml.root(root, encoding),
  File "/usr/local/lib/python3.8/site-packages/stixmarx/xml.py", line 124, in root,
    tree = to_etree(doc, encoding),
  File "/usr/local/lib/python3.8/site-packages/stixmarx/xml.py", line 111, in to_etree,
    return etree.parse(doc, parser=parser),
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse,
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument,
  File "src/lxml/parser.pxi", line 1891, in lxml.etree._parseMemoryDocument,
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.,
Reporting work update_received opencti-work--8da0aebb-35a2-4927-905d-053decf5d17f,
Message (delivery_tag=13) processed, thread terminated
```

[https://us-cert.cisa.gov/sites/default/files/publications/AA21-062A.stix.xml](https://us-cert.cisa.gov/sites/default/files/publications/AA21-062A.stix.xml) 
This sample errors out with:
```
Importing the file https://10.150.4.44/storage/get/import/Report/fd8b363c-e887-40d6-9cf1-2129f0922931/test.xml,
Results produced by the stix2-elevator are not for production purposes.,
[stix2elevator] [ERROR  ] [2021-03-30 20:35:34,397] Error occurred: EntityRef: expecting ';', line 328, column 188 (<string>, line 328),
Error in message processing, reporting error to API,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.8/site-packages/pycti/utils/opencti_stix2_splitter.py", line 50, in split_bundle,
    bundle_data = json.loads(bundle),
  File "/usr/local/lib/python3.8/json/__init__.py", line 341, in loads,
    raise TypeError(f'the JSON object must be str, bytes or bytearray, ',
TypeError: the JSON object must be str, bytes or bytearray, not NoneType,
During handling of the above exception, another exception occurred:,
  File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 123, in _data_handler,
    message = self.callback(json_data["event"]),
  File "import-file-stix.py", line 29, in _process_message,
    bundles_sent = self.helper.send_stix2_bundle(file_content),
  File "/usr/local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 514, in send_stix2_bundle,
    bundles = stix2_splitter.split_bundle(bundle),
  File "/usr/local/lib/python3.8/site-packages/pycti/utils/opencti_stix2_splitter.py", line 52, in split_bundle,
    raise Exception("File data is not a valid JSON"),
Exception: File data is not a valid JSON,
Reporting work update_received opencti-work--b7368a1d-be92-4578-86ef-cbdcaf2885ba,
Message (delivery_tag=17) processed, thread terminated
```

**Comment by nor3th** [comment]
Sry for the late reply. All the errors are caused by the stix elevator [1] and not by the ImportFileStix connector.

>The stix2-elevator is a software tool for converting STIX 1.x XML to STIX 2.0 or 2.1 JSON. Due to the differences between STIX 1.x and STIX 2.x, this conversion is best-effort only. 

Nothing we can do here, the difference between STIX1 and STIX2 is just too big to handle them automatically. You can try converting the Stix 1.1.1 files yourself with the stix-elevator and then manually edit them until they are able to be processed.

[1] https://github.com/oasis-open/cti-stix-elevator

**Comment by SamuelHassine** [comment]
Hello @kudrew,

The connector has been reworked and the stix elevator library has been updated. Please let us know if you still have problem.

Kind regards,
Samuel

**Comment by nor3th** [comment]
Hey @SamuelHassine 

I already tried to import the Stix1 files from @kudrew using the new stix-elevator library, but the issues still persist. Either way, nothing we can really do since the error are caused by the stix-elevator.
