### ISSUE TITLE
IPInfo connector failing at some IP's

### ISSUE THREAD

**Issue by intelwolf** [OpenCTI-Platform/connectors#32]
## Description

At some IP address enrichments the IPInfo connector is throwing an error

## Environment

1. OS (where OpenCTI server runs): Debian
2. OpenCTI version: 2.0.2
3. OpenCTI client: frontend
4. Other environment details: -

## Reproducible Steps

Add a new observable type IP4: 82.146.51.150 with IPInfo connector enabled. Notice that for this IP the connector is throwing an error

## Expected Output
Enrichment of indicator

## Actual Output
Fail in enrichment. Error thrown:

DEBUG:urllib3.connectionpool:https://ipinfo.io:443 "GET /82.146.51.150?token=########## HTTP/1.1" 200 None
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pycti/connector/opencti_connector_helper.py", line 43, in _data_handler
    messages = self.callback(json_data)
  File "ipinfo.py", line 66, in _process_message
    bundle = self._generate_stix_bundle(country, json_data['city'], observable_id)
  File "ipinfo.py", line 26, in _generate_stix_bundle
    'x_opencti_alias': [country.official_name],
  File "/usr/local/lib/python3.7/site-packages/pycountry/db.py", line 23, in __getattr__
    raise AttributeError
AttributeError
INFO:root:Reporting job 3de7d75b-6574-4111-baf2-200e8e36aa09 with status error... 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by intelwolf** [comment]
In not all cases the official_name field is available in the iso3166-1.json country file. If the field is missing the connector throws above error. Falling back to the name field in that case fixes the issue. 
Modification of the code in /opt/opencti-connector-ipinfo/ipinfo.py file of the ipinfo connector fixes the issue:

```
def _generate_stix_bundle(self, country, city, observable_id):
       # Generate stix bundle                                             
        try:                                         
            cname=country.official_name                           
        except:                                      
            cname=country.name                       
        country_identity = Identity(                 
            name=country.name,                   
            identity_class='group',                  
            custom_properties={                      
                'x_opencti_identity_type': 'country',
                'x_opencti_alias': [cname],      
            }                                    
        )                                            

```
