### ISSUE TITLE
MISP connector not working

### ISSUE THREAD

**Issue by maxifjaved** [OpenCTI-Platform/connectors#386]
Not able to connect with MISP

## Description

```
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Variable "$input" got invalid value ["misp"] at "input.scope"; String cannot represent a non string value: ["misp"]
Traceback (most recent call last):
  File "/connectors/misp/src/misp.py", line 1453, in <module>
    mispConnector = Misp()
  File "/connectors/misp/src/misp.py", line 87, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/.local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 409, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/.local/lib/python3.9/site-packages/pycti/api/opencti_api_connector.py", line 101, in register
    result = self.api.query(query, connector.to_input())
  File "/.local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 276, in query
    raise ValueError(
ValueError: {'name': 'Variable "$input" got invalid value ["misp"] at "input.scope"; String cannot represent a non string value: ["misp"]', 'message': 'Variable "$input" got invalid value ["misp"] at "input.scope"; String cannot represent a non string value: ["misp"]'}

```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 21.04
2. OpenCTI version: 4.5.0
3. OpenCTI client: python
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. run opencti backend
2. run misp
3. clone connector
4. go to misp/src and run `python3 misp.py` after installing requirement

## Expected Output

Should connect to misp

## Actual Output

Throw error
 
## Additional information
```
opencti:
  url: 'http://localhost:4000'
  token: '0b2819d5-bdfd-41d6-9367-de4fadf8f43e'
connector:
  id: 'cf3aa2d2-e383-4293-82d4-d35d6f910159' # '6b039104-178a-456d-97ea-e1d7ee6372b8' #'4bb3d648-8309-444f-8a39-c04179ca3f7f' ##
  type: 'EXTERNAL_IMPORT'
  name: 'MISP' # Required
  scope: 'misp'
  confidence_level: 3 # 0 (Unknown) or from 1 to 100
  update_existing_data: False
  log_level: 'info'

misp:
  url: 'https://localhost' # Required
  key: 'WqrSKj30zE5UXAxAtinp0ahyEW6yS8eDAkmxYD1r' # Required
  ssl_verify: False # Required
  create_reports: True # Required, create report for MISP event
  create_indicators: True # Required, create indicators for attributes
  create_observables: True # Required, create observables for attributes
  #report_class: 'misp-event' # Optional, report_class if creating report for event
  import_from_date: '2010-01-01' # Optional, import all event from this date
  import_tags: '' # 'opencti:import,type:osint' # Optional, list of tags used for import events
  import_tags_not: '' # Optional, list of tags to not include
  import_creator_orgs: 'VK-Intel' #'CIRCL,Luatix' # Optional, only import events created by this ORG (put the identifier here)
  import_owner_orgs: 'ORGNAME' # Optional, only import events owned by this ORG (put the identifier here)
  import_distribution_levels: '0,1,2,3' # Optional, only import events with the given distribution levels
  import_threat_levels: '1,2,3,4' # Optional only import events with the given threat levels
  interval: 1 # Required, in minutes

```

**Comment by nor3th** [comment]
I can't reproduce the error. It seems like the input scope "misp" isn't registered in the OpenCTI backend, nothing to do with the MISP connector itself.
I don't have too much insight into the backend workings of OpenCTI, but it seems to me that some DB query fails...

If you have the MISP connector from the git repository, I can imagine that the connector uses version 4.5.4, while OpenCTI itself uses 4.5.0. Maybe try using the same version, but I am not too sure if that is really the issue. The `misp` scope has already been in use for quite a while.

Are the other connectors running without issues? Can you try to destroy the OpenCTI instance with its volumes (docker-compose down -v) and then try again. Please also check the logs of the Elastic, OpenCTI and other support docker instances for errors during the startup before trying to use the MISP connector again.

**Comment by maxifjaved** [comment]
Here is the logs from the OpenCTI.

```
{
   "user":{
      "ip":"::ffff:127.0.0.1",
      "user_id":"88ec0c6a-13ce-5e39-b486-354fe4a7084f"
   },
   "type":"WRITE_ERROR",
   "operation_query":"mutation RegisterConnector($input:RegisterConnectorInput){registerConnector(input:$input){id connector_state config{connection{host use_ssl port user pass}listen listen_exchange push push_exchange}connector_user{id}}}",
   "inner_relation_creation":0,
   "operation":"RegisterConnector",
   "time":1,
   "variables":{
      "input":{
         "id":"cf3aa2d2-e383-4293-82d4-d35d6f910159",
         "name":"MISP",
         "type":"EXTERNAL_IMPORT",
         "scope":[
            "misp"
         ],
         "auto":false,
         "only_contextual":false
      }
   },
   "size":148,
   "error":{
      "stacktrace":[
         "GraphQLError: Variable \"$input\" got invalid value [\"misp\"] at \"input.scope\"; String cannot represent a non string value: [\"misp\"]",
         "at /opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:116:15",
         "at coerceInputValueImpl (/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:131:9)",
         "at coerceInputValueImpl (/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:54:14)",
         "at coerceInputValueImpl (/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:105:34)",
         "at coerceInputValue (/opencti-platform/opencti-graphql/node_modules/graphql/utilities/coerceInputValue.js:37:10)",
         "at _loop (/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:109:69)",
         "at coerceVariableValues (/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:121:16)",
         "at getVariableValues (/opencti-platform/opencti-graphql/node_modules/graphql/execution/values.js:50:19)",
         "at buildExecutionContext (/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:203:61)",
         "at executeImpl (/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:101:20)",
         "at Object.execute (/opencti-platform/opencti-graphql/node_modules/graphql/execution/execute.js:60:35)",
         "at /opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/requestPipeline.js:261:48",
         "at Generator.next (<anonymous>)",
         "at /opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
         "at new Promise (<anonymous>)",
         "at __awaiter (/opencti-platform/opencti-graphql/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)"
      ]
   },
   "category":"APP",
   "version":"4.5.0",
   "level":"error",
   "message":"API Call",
   "timestamp":"2021-06-10T07:04:55.104Z"
}

```

**Comment by nor3th** [comment]
> Are the other connectors running without issues? Can you try to destroy the OpenCTI instance with its volumes (docker-compose down -v) and then try again. Please also check the logs of the Elastic, OpenCTI and other support docker instances for errors during the startup before trying to use the MISP connector again.

**Comment by SamuelHassine** [comment]
Closing this due to inactivity.
