### ISSUE TITLE
[TAXII2] KeyError: 'objects' when pulling TAXII feed

### ISSUE THREAD

**Issue by mwatermolen** [OpenCTI-Platform/connectors#411]
## Description

Seems to be a python parsing error when using the TAXII 2 connector. I tested with the anomali LIMO feed https://limo.anomali.com/api/v1/taxii2/taxii/.

## Environment

1. Ubuntu 20.04 / RKE KUBERNTES
2. OpenCTI version: 4.5.5
3. OpenCTI client: TAXII2 Connector
4. Other environment details: KUBERNTES

### ENV
```
opencti/connector-taxii2:4.5.5
Environment
CONNECTOR_CONFIDENCE_LEVEL: 15
CONNECTOR_ID: 1712b609-0c1b-41e4-9480-2aa142950ca6
CONNECTOR_LOG_LEVEL: info
CONNECTOR_NAME: TAXII2-anomali
CONNECTOR_SCOPE: ipv4-addr,ipv6-addr,vulnerability,domain,url,file-sha256,file-md5,file-sha1
CONNECTOR_TYPE: EXTERNAL_IMPORT
CONNECTOR_UPDATE_EXISTING_DATA: true
OPENCTI_TOKEN: dde6260b-5706-4845-8cbe-c8e9ba55a4b9
OPENCTI_URL: http://opencti-4-1625146660-opencti:8080
TAXII2_COLLECTIONS: *.*
TAXII2_DISCOVERY_URL: https://limo.anomali.com/api/v1/taxii2/taxii
TAXII2_INITIAL_HISTORY: 24
TAXII2_INTERVAL: 100
TAXII2_PASSWORD: guest
TAXII2_USERNAME: guest
TAXII2_V21: false
VERIFY_SSL: true
```

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Set container ENV per image below
2. get no data
3. profit?
![image](https://user-images.githubusercontent.com/73605619/124137304-2ac6b500-da4b-11eb-9cfa-7ef91bc68bd1.png)

## Expected Output

Objects should show up in openCTI

## Actual Output

```
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 1712b609-0c1b-41e4-9480-2aa142950ca6
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:Polling all API Roots
INFO:root:Polling entire API root TAXII feeds
INFO:root:Polling Collection Phish Tank
Traceback (most recent call last):
  File "/opt/opencti-taxii2/taxii2.py", line 265, in <module>
    raise e
  File "/opt/opencti-taxii2/taxii2.py", line 263, in <module>
    CONNECTOR.run()
  File "/opt/opencti-taxii2/taxii2.py", line 125, in run
    self.poll_all_roots(coll_title)
  File "/opt/opencti-taxii2/taxii2.py", line 152, in poll_all_roots
    self.poll_entire_root(root)
  File "/opt/opencti-taxii2/taxii2.py", line 181, in poll_entire_root
    self.poll(coll)
  File "/opt/opencti-taxii2/taxii2.py", line 206, in poll
    self.send_to_server(collection.get_objects(**filters))
  File "/opt/opencti-taxii2/taxii2.py", line 216, in send_to_server
    f"Sending Bundle to server with " f'{len(bundle["objects"])} objects'
KeyError: 'objects'
```
 
## Additional information

{ Any additional information, including logs or screenshots if you have any. }

**Comment by mwatermolen** [comment]
@SamuelHassine Is there anything further I can provide on this issue?

**Comment by nor3th** [comment]
Do you have any other info on the crash you could share? Do you have any info on the bundle which created that issue?

Since `objects` isn't present in that bundle, it seems like an incomplete bundle at all.

**Comment by SamuelHassine** [comment]
@jbfeldman Any idea on this issue?

**Comment by SamuelHassine** [comment]
@jbfeldman Any update?
