### ISSUE TITLE
ERROR:root:Variable "$input" got invalid value

### ISSUE THREAD

**Issue by khalidrehan** [OpenCTI-Platform/connectors#428]
## Description

**Development Mode, not the deployment packs.**

On Manual install, all connectors don't run and the output error is:
```
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Variable "$input" got invalid value...................
```

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04.1
2. OpenCTI version: 4.5
4. Other environment details: Python 3.8, pip 21.1.3.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
0. At least one worker is running.
1. Edit config.yml
2. pip3 install -r requirements.txt 
3. python3 connector.py

## Expected Output
Connector on

## Actual Output

**Sample:**
```
cti@cti:/usr/share/cti/connectors/mitre/src$ python3 mitre.py
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Variable "$input" got invalid value ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"] at "input.scope"; String cannot represent a non string value: ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"]
{'name': 'Variable "$input" got invalid value ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"] at "input.scope"; String cannot represent a non string value: ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"]', 'message': 'Variable "$input" got invalid value ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"] at "input.scope"; String cannot represent a non string value: ["identity", "attack-pattern", "course-of-action", "intrusion-set", "malware", "tool", "report", "external-reference-as-report"]'}


cti@cti:/usr/share/cti/connectors/alienvault/src$ python3 main.py
INFO:root:Listing Threat-Actors with filters null.
ERROR:root:Variable "$input" got invalid value ["alienvault"] at "input.scope"; String cannot represent a non string value: ["alienvault"]
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    connector = AlienVault()
  File "/usr/share/cti/connectors/alienvault/src/alienvault/core.py", line 130, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/home/tip/.local/lib/python3.8/site-packages/pycti/connector/opencti_connector_helper.py", line 372, in __init__
    connector_configuration = self.api.connector.register(self.connector)
  File "/home/tip/.local/lib/python3.8/site-packages/pycti/api/opencti_api_connector.py", line 101, in register
    result = self.api.query(query, connector.to_input())
  File "/home/tip/.local/lib/python3.8/site-packages/pycti/api/opencti_api_client.py", line 278, in query
    raise ValueError(
ValueError: {'name': 'Variable "$input" got invalid value ["alienvault"] at "input.scope"; String cannot represent a non string value: ["alienvault"]', 'message': 'Variable "$input" got invalid value ["alienvault"] at "input.scope"; String cannot represent a non string value: ["alienvault"]'}

```
Reference: issue https://github.com/OpenCTI-Platform/opencti/issues/1461

Looping @maxifjaved

Regards,
Khalid..

**Comment by khalidrehan** [comment]
I noticed this as well:

```
cti@cti:~$ curl localhost:4000
<!doctype html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><link rel="shortcut icon" href="/static/favicon.png"/><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/><script>window.BASE_PATH=""</script><meta name="viewport" content="width=device-width,initial-scale=1"/><title>TIPX - Cyber Threat Intelligence Platform</title><link href="/static/css/2.7f79ea35.chunk.css" rel="stylesheet"><link href="/static/css/main.45e8f8cb.chunk.css" rel="stylesheet"></head><body><div id="root"></div><script>!function(e){function t(t){for(var n,f,i=t[0],l=t[1],p=t[2],c=0,s=[];c<i.length;c++)f=i[c],Object.prototype.hasOwnProperty.call(o,f)&&o[f]&&s.push(o[f][0]),o[f]=0;for(n in l)Object.prototype.hasOwnProperty.call(l,n)&&(e[n]=l[n]);for(a&&a(t);s.length;)s.shift()();return u.push.apply(u,p||[]),r()}function r(){for(var e,t=0;t<u.length;t++){for(var r=u[t],n=!0,i=1;i<r.length;i++){var l=r[i];0!==o[l]&&(n=!1)}n&&(u.splice(t--,1),e=f(f.s=r[0]))}return e}var n={},o={1:0},u=[];function f(t){if(n[t])return n[t].exports;var r=n[t]={i:t,l:!1,exports:{}};return e[t].call(r.exports,r,r.exports,f),r.l=!0,r.exports}f.m=e,f.c=n,f.d=function(e,t,r){f.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},f.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},f.t=function(e,t){if(1&t&&(e=f(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(f.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)f.d(r,n,function(t){return e[t]}.bind(null,n));return r},f.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return f.d(t,"a",t),t},f.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},f.p="/";var i=this["webpackJsonpopencti-front"]=this["webpackJsonpopencti-front"]||[],l=i.push.bind(i);i.push=t,i=i.slice();for(var p=0;p<i.length;p++)t(i[p]);var a=l;r()}([])</script><script src="/static/js/2.95d52f6e.chunk.js"></script><script src="/static/js/main.702b98f4.chunk.js"></script></body></html>
cti@cti:~$
```

**Comment by nor3th** [comment]
Closed due to inactivity
