### ISSUE TITLE
MISP Connector Fails with Key Error for EventReport

### ISSUE THREAD

**Issue by GRIT-5ynax** [OpenCTI-Platform/connectors#440]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

The following traceback shows the key error when running the MISP connector.
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 1515, in <module>
    mispConnector.run()
  File "/opt/opencti-connector-misp/misp.py", line 253, in run
    self.process_events(work_id, events)
  File "/opt/opencti-connector-misp/misp.py", line 611, in process_events
    for note in event["Event"]["EventReport"]:
KeyError: 'EventReport'

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 4.5.5
3. OpenCTI client: Frontend
4. Other environment details: Running via docker

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add MISP connector/service config to docker configuration file
2. Deploy
3. Receive traceback (full logs below)

## Expected Output

No Key errors

## Actual Output

Key error for EventReport
 
## Additional information

INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 014f0e8c-8af2-4ba5-aae9-d7159e70cdf9
INFO:root:Starting ping alive thread
INFO:pymisp:The version of PyMISP recommended by the MISP instance (response['version']) is older than the one you're using now (2.4.144). If you have a problem, please upgrade the MISP instance or use an older PyMISP version.
INFO:root:Initiate work for 014f0e8c-8af2-4ba5-aae9-d7159e70cdf9
INFO:root:Connector last run: 2021-08-06 19:26:59
INFO:root:Fetching MISP events with args: {"timestamp": 1628278019, "limit": 50, "page": 1}
INFO:root:MISP returned 0 events.
INFO:root:Connector successfully run (0 events have been processed), storing last_run as 1628278053
INFO:root:Reporting work update_received opencti-work--b5b2b596-0602-49db-96cb-771e01b74375
INFO:root:Connector state has been remotely reset to: "None"
INFO:root:Initiate work for 014f0e8c-8af2-4ba5-aae9-d7159e70cdf9
INFO:root:Connector has never run
INFO:root:Fetching MISP events with args: {"date_from": "2000-01-01", "limit": 50, "page": 1}
INFO:root:MISP returned 30 events.
INFO:root:Processing event 7a963580-5728-4cbf-8443-3b7183e167f3
Traceback (most recent call last):
  File "/opt/opencti-connector-misp/misp.py", line 1515, in <module>
    mispConnector.run()
  File "/opt/opencti-connector-misp/misp.py", line 253, in run
    self.process_events(work_id, events)
  File "/opt/opencti-connector-misp/misp.py", line 611, in process_events
    for note in event["Event"]["EventReport"]:
KeyError: 'EventReport'

**Comment by GRIT-5ynax** [comment]
Closing since I need to learn how to read. (Updated MISP)
