### ISSUE TITLE
[CAPE] connection refused 

### ISSUE THREAD

**Issue by kboulom** [OpenCTI-Platform/connectors#558]
## Description
Connection refused error on the cape connector to the API

## Environment

1. OS (where OpenCTI server runs): Debian 10
2. OpenCTI version: 5.0.3
3. cape Version: Rolling

## Reproducible Steps

install OpenCTI core
Create users for connectors (get token)
add connector to docker-compose.yml
configure .env with ID and Token
re-run docker-compose -f docker-compose.yml up -d 

## Expected Output

get content

## Actual Output

`INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: f926760f-f54c-46f8-86d0-78eecff858cf
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:None
ERROR:root:Error connecting to Cape API
ERROR:root:HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3121751a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f3121751a30>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3121751a30>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-cape/main.py", line 187, in <module>
    raise e
  File "/opt/opencti-cape/main.py", line 185, in <module>
    CONNECTOR.run()
  File "/opt/opencti-cape/main.py", line 133, in run
    raise (err)
  File "/opt/opencti-cape/main.py", line 128, in run
    self.cape_api.getCuckooTasks()
  File "/opt/opencti-cape/cape/cape.py", line 806, in getCuckooTasks
    response = self._make_request(Method, EP)
  File "/opt/opencti-cape/cape/cape.py", line 837, in _make_request
    resp = requests.request(method, URL, verify=self.verify)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f3121751a30>: Failed to establish a new connection: [Errno 111] Connection refused'))
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: f926760f-f54c-46f8-86d0-78eecff858cf
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:None
ERROR:root:Error connecting to Cape API
ERROR:root:HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f03896c7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f03896c7c10>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f03896c7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-cape/main.py", line 187, in <module>
    raise e
  File "/opt/opencti-cape/main.py", line 185, in <module>
    CONNECTOR.run()
  File "/opt/opencti-cape/main.py", line 133, in run
    raise (err)
  File "/opt/opencti-cape/main.py", line 128, in run
    self.cape_api.getCuckooTasks()
  File "/opt/opencti-cape/cape/cape.py", line 806, in getCuckooTasks
    response = self._make_request(Method, EP)
  File "/opt/opencti-cape/cape/cape.py", line 837, in _make_request
    resp = requests.request(method, URL, verify=self.verify)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f03896c7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by nor3th** [comment]
Hey @kboulom 

```requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /apiv2/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f03896c7c10>: Failed to establish a new connection: [Errno 111] Connection refused'))```

It seems like the CAPE server's domain `sandbox.no` doesn't allow connections to port 443. From my side it looks like `sandbox.no` is a parked domain with no server listening to port 443.

Regards,

**Comment by nor3th** [comment]
Closed due to inactivity.
