### ISSUE TITLE
Unable to connect any connector

### ISSUE THREAD

**Issue by seccodingwizard** [OpenCTI-Platform/connectors#583]
## Description

Unable to connect any connector.

## Environment

1. OS (where OpenCTI server runs):  Ubuntu 1 20.8
2. OpenCTI version: 5.1.2
3. OpenCTI client: python 3.8
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. when we run the connector in src mitre.py , we getting the error and stopping opencti service.

## Actual Output

/opencti/opencti/node_modules/amqplib/lib/channel.js:422
    var error = new Error(emsg);
                ^
Error: Channel closed by server: 403 (ACCESS-REFUSED) with message "ACCESS_REFUSED - access to queue 'listen_6f3db665-726c-4a2d-8329-09c099515d59' in vhost '/' refused for user 'admin'"
    at ConfirmChannel.C.accept (/opencti/opencti/node_modules/amqplib/lib/channel.js:422:17)
    at Connection.mainAccept [as accept] (/opencti/opencti/node_modules/amqplib/lib/connection.js:64:33)
    at Socket.go (/opencti/opencti/node_modules/amqplib/lib/connection.js:478:48)
    at Socket.emit (events.js:400:28)
    at emitReadable_ (internal/streams/readable.js:555:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[10]+  Exit 1                  sudo yarn serv  (wd: /opencti/opencti)

**Comment by seccodingwizard** [comment]
Hi team,

Any update , all my connector throwing same error, i am suspecting the rabitmq.

Regards,
Raghunandan

**Comment by nor3th** [comment]
Hey @seccodingwizard 

it seems like RabbitMQ is refusing access, please make sure that the RabbitMQ credentials are set properly.

Regards

**Comment by nor3th** [comment]
Closed to due inactivity
