### ISSUE TITLE
[elastic] Elastic Threat Intel Connector: AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by pbonfa** [OpenCTI-Platform/connectors#592]
I'm running OpenCti 5.1.3 on docker; I have a problem with Elastic Threat Intel Connector:

[2021-12-28T10:08:21.872][INFO] Connected to Elasticsearch
[2021-12-28T10:08:21.872][INFO] Setting up Elasticsearch for OpenCTI Connector
[2021-12-28T10:08:21.882][INFO] Installing index template: opencti
[2021-12-28T10:08:21.888][INFO] Index already exists
[2021-12-28T10:08:21.891][INFO] Signals manager thread initialized
[2021-12-28T10:08:21.891][INFO] Signals manager thread starting
[2021-12-28T10:13:55.577][ERROR] Data type unsupported: identity. Only 'indicators are currently supported.
[2021-12-28T10:13:56.275][ERROR] Data type unsupported: identity. Only 'indicators are currently supported.
[2021-12-28T10:43:56.003][ERROR] Data type unsupported: identity. Only 'indicators are currently supported.
[2021-12-28T14:29:54.954][ERROR] Data type unsupported: url. Only 'indicators are currently supported.
[2021-12-28T14:30:00.685][WARNING] _parse() not implemented for `url`
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/runtime/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 365, in run
    self.callback(msg)
  File "/runtime/lib/python3.9/site-packages/elastic/elastic.py", line 147, in _process_message
    round(int(event_id.split("-")[0]) / 1000), tz=timezone.utc
AttributeError: 'NoneType' object has no attribute 'split'

Can you help me ?
regards.

**Comment by nor3th** [comment]
Hey @pbonfa 

What does your elastic connector config look like?

Regardss

**Comment by pbonfa** [comment]
> 

Hi, this is the config:
connector-elastic:
    image: opencti/connector-elastic:5.1.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=xxxxx
      - CONNECTOR_ID=yyyyy
      - CONNECTOR_TYPE=STREAM
      - CONNECTOR_LIVE_STREAM_ID=live # ID of the live stream created in the OpenCTI UI
      - "CONNECTOR_NAME=OpenCTI Elastic Connector"
      - CONNECTOR_SCOPE=elastic
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - "CONNECTOR_ENTITY_NAME=Elastic Detection Cluster"
      - "CONNECTOR_ENTITY_DESCRIPTION=Elasticsearch detection engine cluster"
      - CONNECTOR_MODE=ecs # Options
      - ELASTICSEARCH_HOSTS=ipofelasticserver
      - ELASTICSEARCH_USERNAME=usertologintoelastic
      - ELASTICSEARCH_PASSWORD=password
      - ELASTICSEARCH_SSL_VERIFY=false
    restart: always

**Comment by nor3th** [comment]
Hey @pbonfa 

This is a bit odd, the `msg.id` sent over by opencti is Null, (https://github.com/OpenCTI-Platform/connectors/blob/master/stream/elastic/elastic/elastic.py#L141-L148)  @SamuelHassine Any ideas?

Regards

**Comment by nor3th** [comment]
@dcode Could you take a look at this please?

**Comment by dcode** [comment]
I'm not sure why `msg.id` is `null`, but @pbonfa if the connector is in "ecs" mode, it only pushes over STIX indicator objects. It looks like maybe your stream is setup to push everything.

Here's the filter that I'm using on my stream, for example.

<img width="363" alt="image" src="https://user-images.githubusercontent.com/171574/152565380-ff49ffb9-0091-4b31-aa90-429539bd3d25.png">

**Comment by pbonfa** [comment]
> many thanks, with this filter applied to stream it works fine! (I also upgraded to version 5.1.4)
