### ISSUE TITLE
[ImportDocument] Unable to run connector from context of Report

### ISSUE THREAD

**Issue by securitiz** [OpenCTI-Platform/connectors#596]
## Description

Before, it was possible to run the ImportDocument connector from within the context of a report (Report -> Data -> Import).

This was useful because it would ensure that the imported data would end up inside the Report

Now, upon running ImportDocument, it returns the following error: "We encountered an internal error. Please try again".

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04
2. OpenCTI version: OpenCTI 5.1.3
3. OpenCTI client: frontend
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Select a report
2. Select Data
3. Upload a file
4. Import the file with the ImportDocument connector

## Expected Output

the data is imported into the Report (or at least, passed on to the validation step)

## Actual Output

Internal error
 
## Additional information

This has been the case for TXT files, PDF files, and freetext

**Comment by nor3th** [comment]
Hey @securitiz 

Could you please post the logs from the connector? Maybe also have a look at the opencti platform logs, since internal error should be visible there.

Regards

**Comment by securitiz** [comment]
[ImportDocument_logs.txt](https://github.com/OpenCTI-Platform/connectors/files/7873344/ImportDocument_logs.txt)

Let me know if this is helpful or I should send additional logs

**Comment by nor3th** [comment]
```
2022-01-14T14:57:49.554-06:00	INFO:root:Listing Malwares with filters null.
2022-01-14T14:57:59.989-06:00	DEBUG:urllib3.connectionpool:http://api.opencti-staging.[redacted].internal:8080 "POST /graphql HTTP/1.1" 200 None
2022-01-14T14:58:00.478-06:00	ERROR:root:We encountered an internal error. Please try again.
2022-01-14T14:58:00.487-06:00	ERROR:root:Error in message processing, reporting error to API
2022-01-14T14:58:00.487-06:00	Traceback (most recent call last):
2022-01-14T14:58:00.487-06:00	File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler
2022-01-14T14:58:00.487-06:00	message = self.callback(json_data["event"])
2022-01-14T14:58:00.487-06:00	File "/opt/opencti-connector-import-document/reportimporter/core.py", line 78, in _process_message
2022-01-14T14:58:00.487-06:00	entity_indicators = self._collect_stix_objects(self.entity_config)
2022-01-14T14:58:00.487-06:00	File "/opt/opencti-connector-import-document/reportimporter/core.py", line 131, in _collect_stix_objects
2022-01-14T14:58:00.487-06:00	entries = custom_function.list(
2022-01-14T14:58:00.487-06:00	File "/usr/local/lib/python3.9/site-packages/pycti/entities/opencti_malware.py", line 195, in list
2022-01-14T14:58:00.487-06:00	result = self.opencti.query(
2022-01-14T14:58:00.487-06:00	File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 314, in query
2022-01-14T14:58:00.487-06:00	raise ValueError(
2022-01-14T14:58:00.487-06:00	ValueError: {'name': 'We encountered an internal error. Please try again.', 'message': 'We encountered an internal error. Please try again.'}
```

There was an issue while querying the malware entities. What do the platform logs say? Some error should be present there

Regards

**Comment by securitiz** [comment]
thanks for the heads up about platform logs @nor3th - looks like its an issue with Minio, not the connector
