### ISSUE TITLE
VirusTotal Connector TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Zhindonm** [OpenCTI-Platform/connectors#614]
## Description

When attempting to enrich an observable such as a SHA256 hash, the enrichment fails and throws an error

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Open file observable
2. Click enrichment
3. Click Virustotal

## Expected Output

Data enrichment

## Actual Output

Error
 
## Additional information

```
INFO:root:Listing Threat-Actors with filters null.,
INFO:root:Connector registered with ID: 8fca7b12-84f5-11ec-a8a3-0242ac120002,
INFO:root:Starting ping alive thread,
INFO:virustotal.client:[VirusTotal] URL: https://www.virustotal.com/api/v3,
INFO:pika.adapters.utils.connection_workflow:Pika version 1.2.0 connecting to ('172.19.0.4', 5672),
INFO:pika.adapters.utils.io_services_utils:Socket connected: <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.19.0.19', 56116), raddr=('172.19.0.4', 5672)>,
INFO:pika.adapters.utils.connection_workflow:Streaming transport linked up: (<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f47261a1190>, _StreamingProtocolShim: <SelectConnection PROTOCOL transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f47261a1190> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>).,
INFO:pika.adapters.utils.connection_workflow:AMQPConnector - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f47261a1190> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>,
INFO:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting success: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f47261a1190> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>,
INFO:pika.adapters.blocking_connection:Connection workflow succeeded: <SelectConnection OPEN transport=<pika.adapters.utils.io_services_utils._AsyncPlaintextTransport object at 0x7f47261a1190> params=<ConnectionParameters host=rabbitmq port=5672 virtual_host=/ ssl=False>>,
INFO:pika.adapters.blocking_connection:Created channel=1,
INFO:root:Reporting work update_received opencti-work--d455e3bb-6e52-4b26-9197-f50d3a7f31c2,
INFO:root:Reading StixCyberObservable {fedd589c-1f1a-41c0-b9f1-921335d1660a}.,
ERROR:root:Error in message processing, reporting error to API,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler,
    message = self.callback(json_data["event"]),
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 195, in _process_message,
    for marking_definition in observable["objectMarking"]:,
TypeError: 'NoneType' object is not subscriptable,
INFO:root:Reporting work update_received opencti-work--d455e3bb-6e52-4b26-9197-f50d3a7f31c2,
INFO:root:Message (delivery_tag=1) processed, thread terminated,
INFO:root:Reporting work update_received opencti-work--a255eda2-1849-4c71-a900-548eb59ad741,
INFO:root:Reading StixCyberObservable {e5f28449-582e-4254-aed1-92c4799db6d4}.,
ERROR:root:Error in message processing, reporting error to API,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler,
    message = self.callback(json_data["event"]),
  File "/opt/opencti-connector-virustotal/virustotal/virustotal.py", line 195, in _process_message,
    for marking_definition in observable["objectMarking"]:,
TypeError: 'NoneType' object is not subscriptable,
INFO:root:Reporting work update_received opencti-work--a255eda2-1849-4c71-a900-548eb59ad741,
INFO:root:Message (delivery_tag=2) processed, thread terminated
```

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/32451415/152363640-144237a7-95de-44f3-b3f6-48834d948788.png)

**Comment by nor3th** [comment]
Hey @Zhindonm 

Thanks for reporting this issue. Please use the `rolling` docker container, which will incorporate this fix.

Regards
