### ISSUE TITLE
opencti api unreachable and connector exit code 1

### ISSUE THREAD

**Issue by kraken8585** [OpenCTI-Platform/connectors#618]
## Description

Hi guys,

I'm getting the following error below with opencti api and misp/alienvault connectors. Any idea what could be wrong with the build? I have no issues accessing the openCTI platform on my localhost

## Environment

1. OS (where OpenCTI server runs): Windows 10 / localhost
2. OpenCTI version: 5.1.4

connector-misp_1 | INFO:root:Listing Threat-Actors with filters null.
connector-misp_1 | Traceback (most recent call last):
connector-misp_1 | File "/opt/opencti-connector-misp/misp.py", line 1696, in
connector-misp_1 | mispConnector = Misp()
connector-misp_1 | File "/opt/opencti-connector-misp/misp.py", line 83, in init
connector-misp_1 | self.helper = OpenCTIConnectorHelper(config)
connector-misp_1 | File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in init
connector-misp_1 | self.api = OpenCTIApiClient(
connector-misp_1 | File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in init
connector-misp_1 | raise ValueError(
connector-misp_1 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
docker_connector-misp_1 exited with code 1
connector-alienvault_1 | INFO:root:Listing Threat-Actors with filters null.
connector-alienvault_1 | Traceback (most recent call last):
connector-alienvault_1 | File "/opt/opencti-connector-alienvault/main.py", line 7, in
connector-alienvault_1 | connector = AlienVault()
connector-alienvault_1 | File "/opt/opencti-connector-alienvault/alienvault/core.py", line 154, in init
connector-alienvault_1 | self.helper = OpenCTIConnectorHelper(config)
connector-alienvault_1 | File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in init
connector-alienvault_1 | self.api = OpenCTIApiClient(
connector-alienvault_1 | File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in init
connector-alienvault_1 | raise ValueError(
connector-alienvault_1 | ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
docker_connector-alienvault_1 exited with code 1

**Comment by kraken8585** [comment]
fixed
