### ISSUE TITLE
Alienvault Connector 5.2.1 "In Progress" Issue

### ISSUE THREAD

**Issue by thev0yager** [OpenCTI-Platform/connectors#630]
I have been working on setting up a single node OpenCTI platform for my organization and am running into a problem with the alientvault connector. I have an api key and have it running in the platform and the status is "In Progress", but it doesn't seem to be pulling any data. After checking the logs of the alienvault connector container I am met with this error message.

I am really not sure what the error code -3 means in I am guessing it has something to do with my network configuration for the containers but I would love another set of eyes on this.

`INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: fda6c391-0907-4adb-87d9-8f4eef9f7d6b
INFO:root:Starting ping alive thread
INFO:root:Starting AlienVault connector...
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {}
INFO:root:Connector first run
INFO:root:Initiate work for fda6c391-0907-4adb-87d9-8f4eef9f7d6b
INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False, relationships: True, patterns_indicates: True)...
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1e045b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1dfee20>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1dfeca0>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1e043a0>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1e04220>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f6fe1ba7940>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 813, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1ba7940>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 8, in <module>
    connector.run()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 247, in run
    pulse_import_state = self.pulse_importer.run(current_state, work_id)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 94, in run
    pulses = self._fetch_subscribed_pulses(latest_pulse_datetime)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 154, in _fetch_subscribed_pulses
    pulses = self.client.get_pulses_subscribed(modified_since)
  File "/opt/opencti-connector-alienvault/alienvault/client.py", line 27, in get_pulses_subscribed
    pulse_data = self.otx.getsince(modified_since, limit=limit)
  File "/usr/local/lib/python3.9/site-packages/OTXv2.py", line 431, in getsince
    return self.getall(limit=limit, modified_since=timestamp, max_page=max_page, max_items=max_items, iter=False)
  File "/usr/local/lib/python3.9/site-packages/OTXv2.py", line 404, in getall
    return self.walkapi(
  File "/usr/local/lib/python3.9/site-packages/OTXv2.py", line 385, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page, max_items=max_items, method=method, body=body))
  File "/usr/local/lib/python3.9/site-packages/OTXv2.py", line 366, in walkapi_iter
    data = self.get(next_page_url)
  File "/usr/local/lib/python3.9/site-packages/OTXv2.py", line 178, in get
    response = self.session().get(
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1ba7940>: Failed to establish a new connection: [Errno -3] Try again'))`

**Comment by nor3th** [comment]
Hey @thev0yager 

The error
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1e045b0>: Failed to establish a new connection: [Errno -3] Try again')': /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00
``` 
indicates, that the url `/api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00` isn't reachable. Obviously it is missing the AlienVault domain. Is the `ALIENVAULT_BASE_URL` env variable set?

Regards

**Comment by thev0yager** [comment]
I have the ALIENVAULT_BASE_URL set to https://otx.alienvault.com I brought this up to a friend at work and they say it could be a crt issue. I tried setting up 2 other connectors and they all gave back the same error (-3). Could this be the case?

**Comment by nor3th** [comment]
Yes you are correct there, I didn't read the `requests.exceptions.ConnectionError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6fe1ba7940>: Failed to establish a new connection: [Errno -3] Try again'))` log entry, where the domain is defined.

It seems that based on this log `File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
for res in _socket.getaddrinfo(host, port, family, type, proto, flags):` the connector is unable to resolve the domain. Maybe check your DNS setup for the connector.

You can do a simple ping/dns lookup from within your container to verify that your connector is unable to resolve external domain names (maybe you need to first install ping since the containers are kept with minimal additional applications). 
```
$ docker exec -it <mycontainer> bash
> ping google.com
```
