### ISSUE TITLE
CAPE / Cuckoo Connector "in progress" issue

### ISSUE THREAD

**Issue by Oddluo** [OpenCTI-Platform/connectors#636]
I checked it through the docker log.

CONNECTOR = cuckooConnector()
  File "/opt/opencti-cuckoo/main.py", line 23, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-cuckoo/main.py", line 191, in <module>
    raise e
  File "/opt/opencti-cuckoo/main.py", line 188, in <module>
    CONNECTOR = cuckooConnector()
  File "/opt/opencti-cuckoo/main.py", line 23, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
Traceback (most recent call last):
  File "/opt/opencti-cuckoo/main.py", line 191, in <module>
    raise e
  File "/opt/opencti-cuckoo/main.py", line 188, in <module>
    CONNECTOR = cuckooConnector()
  File "/opt/opencti-cuckoo/main.py", line 23, in __init__
    self.helper = OpenCTIConnectorHelper(config)
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 459, in __init__
    self.api = OpenCTIApiClient(
  File "/usr/local/lib/python3.9/site-packages/pycti/api/opencti_api_client.py", line 179, in __init__
    raise ValueError(
ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: bbb
INFO:root:Starting ping alive thread
INFO:root:Connector has never run
INFO:root:None
ERROR:root:Error connecting to Cuckoo API
ERROR:root:HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /api/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc9478b040>: Failed to establish a new connection: [Errno 111] Connection refused'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdc9478b040>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /api/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc9478b040>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-cuckoo/main.py", line 191, in <module>
    raise e
  File "/opt/opencti-cuckoo/main.py", line 189, in <module>
    CONNECTOR.run()
  File "/opt/opencti-cuckoo/main.py", line 137, in run
    raise (err)
  File "/opt/opencti-cuckoo/main.py", line 132, in run
    self.cuckoo_api.getCuckooTasks()
  File "/opt/opencti-cuckoo/cuckoo/cuckoo.py", line 704, in getCuckooTasks
    response = self._make_request(Method, EP)
  File "/opt/opencti-cuckoo/cuckoo/cuckoo.py", line 735, in _make_request
    resp = requests.request(method, URL, verify=self.verify)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='sandbox.no', port=443): Max retries exceeded with url: /api/tasks/list (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdc9478b040>: Failed to establish a new connection: [Errno 111] Connection refused'))

the first error is ValueError: OpenCTI API is not reachable, but it is the same like other connectors ...

**Comment by Oddluo** [comment]
@nor3th hey bro, it seems like the default config is wrong. can you give me a correct docker-compose.yml about the CAPE / Cuckoo? the url sandbox.no is wrong , and i've tried sandbox.io , but It's API is not found.

![图片](https://user-images.githubusercontent.com/67694128/160037671-c73f38ec-3e8f-497b-b07f-3f61952b2cfb.png)

**Comment by nor3th** [comment]
@mwatermolen Do you know what the correct settings are? If they changed, could you please adapt them.

**Comment by mwatermolen** [comment]
Hey @nor3th, What is the URL of the sandbox you have setup. It needs a valid Cuckoo URL, sandbox[.]io / sandbox[.]no are placeholders. To my knowledge there isnt a hosted Cuckoo instance. @Oddluo are you running a cuckoo sandbox instance?

**Comment by nor3th** [comment]
This would then also explain the same issue here #558

**Comment by mwatermolen** [comment]
Ahh yep, its BYO(Instance) lol
