### ISSUE TITLE
[import-document] Unable to import pdf report attached to malware

### ISSUE THREAD

**Issue by mikepemdi** [OpenCTI-Platform/connectors#645]
## Description
When trying to import data from something in the malware arsenal the ImportDocument connector creates an error:

```
[Mar 28, 2022, 2:28:08 PM] Connector ready to process the operation
[Mar 28, 2022, 2:28:19 PM] Invalid value for Bundle 'objects': No values for required properties for Malware: (is_family).
```

## Environment
ImportDocument Connector
OpenCTI version: 5.2.3

**Comment by nor3th** [comment]
Hey @mikepemdi 

Could you please share the file you are trying to import so we can try to reproduce the issue.

Regards

**Comment by mikepemdi** [comment]
yup it pretty much happens with any of them, i will attach a screenshot and this test pdf file i was using
<img width="854" alt="Screen Shot 2022-03-28 at 2 38 45 PM" src="https://user-images.githubusercontent.com/95925727/160484695-935b04a2-5381-4b0b-8ffc-bb739a876b6b.png">
[testing-intel.pdf](https://github.com/OpenCTI-Platform/connectors/files/8366206/testing-intel.pdf)

**Comment by nor3th** [comment]
Thanks a lot, Could you please run the connector again with debug logging activated and post the logs. This behavior is a bit odd since the connector does not add any new Malware SDOs and only queries the OpenCTI platform...
https://github.com/OpenCTI-Platform/connectors/tree/master/internal-import-file/import-document#debugging

**Comment by mikepemdi** [comment]
```
INFO:root:Parsing report testing-intel.pdf application/pdf
DEBUG:root:Observable match: google.commicrosoft.com
DEBUG:root:Filter regex 're.compile('\\bfireeye\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bcrowdstrike\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bf-secure\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bkaspersky\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bgdata\\.de\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bcylance\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\beset\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\btrendmicro\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bwelivesecurity\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bsecurelist\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\b\\.zip$\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Filter regex 're.compile('\\bwikipedia\\.com\\b', re.IGNORECASE)' for value 'google.commicrosoft.com'
DEBUG:root:Text: 'google.commicrosoft.com' -> extracts {'google.commicrosoft.com': {'type': 'observable', 'category': 'Domain-Name.value', 'match': 'google.commicrosoft.com', 'range': (0, 23)}}
DEBUG:root:Results: [{'type': 'observable', 'category': 'Domain-Name.value', 'match': 'google.commicrosoft.com', 'range': (0, 23)}]
INFO:root:Reading Malware {SCRUBBED-UUID-FROM-LOG}.
DEBUG:urllib3.connectionpool:http://SCRUBBED-DOMAIN-FROM-LOG:8080 "POST /graphql HTTP/1.1" 200 1133
DEBUG:urllib3.connectionpool:http://SCRUBBED-DOMAIN-FROM-LOG:8080 "GET /storage/get/import/Malware/SCRUBBED-UUID-FROM-LOG/testing-intel.pdf HTTP/1.1" 200 None
ERROR:root:Error in message processing, reporting error to API
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/stix2/base.py", line 50, in _check_property
    kwargs[prop_name], has_custom = prop.clean(
  File "/usr/local/lib/python3.9/site-packages/stix2/properties.py", line 240, in clean
    valid, temp_custom = self.contained.clean(item, allow_custom)
  File "/usr/local/lib/python3.9/site-packages/stix2/properties.py", line 879, in clean
    parsed_obj = parse(dictified, allow_custom=allow_custom)
  File "/usr/local/lib/python3.9/site-packages/stix2/parsing.py", line 40, in parse
    obj = dict_to_stix2(obj, allow_custom, version)
  File "/usr/local/lib/python3.9/site-packages/stix2/parsing.py", line 99, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, **stix_dict)
  File "/usr/local/lib/python3.9/site-packages/stix2/base.py", line 215, in __init__
    raise MissingPropertiesError(cls, missing_kwargs)
stix2.exceptions.MissingPropertiesError: No values for required properties for Malware: (is_family).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 163, in _data_handler
    message = self.callback(json_data["event"])
  File "/opt/opencti-connector-import-document/reportimporter/core.py", line 92, in _process_message
    observable_cnt = self._process_parsed_objects(
  File "/opt/opencti-connector-import-document/reportimporter/core.py", line 265, in _process_parsed_objects
    bundle = Bundle(objects=observables, allow_custom=True).serialize()
  File "/usr/local/lib/python3.9/site-packages/stix2/v21/bundle.py", line 35, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/stix2/base.py", line 203, in __init__
    temp_custom = self._check_property(
  File "/usr/local/lib/python3.9/site-packages/stix2/base.py", line 58, in _check_property
    raise InvalidValueError(
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': No values for required properties for Malware: (is_family).
```

**Comment by nor3th** [comment]
Hey @mikepemdi 

I think I have found the issue. I initially wrote the connector to import pdf files as Reports see here for details (https://luatix.notion.site/Import-Export-7dc143dfbb6147b0881080487ed9db33#69298813e2604f7ab98918bfc4d4c92e).

I wasn't aware that the data page of the different SDOs are also able to interact with the connector, but since the connector is designed to convert the content of pdf files into STIX Reports, it won't work for ie. malware entities, where OpenCTI would expect some other STIX entities from the connector.

Hence you can freely use the connector to import reports, but I have to figure out if this is a mere configuration mistake on our side that the connector is available for malware entities or if it is an intended use case and thus we need to adapt the functionality of the connector.
@SamuelHassine thoughts?

Regards

**Comment by SamuelHassine** [comment]
@nor3th Can you just implement the is_family to true by default in the generated bundle?

**Comment by nor3th** [comment]
Sure, I'll have to test the import functionality for all the different SDOs as well. Will take some time
