### ISSUE TITLE
[Splunk] Connector failed TypeError: can only concatenate str (not "Event") to str

### ISSUE THREAD

**Issue by Vieteg** [OpenCTI-Platform/connectors#649]
## Description

Splunk connector fails during export of some records from OpenCTI. Encountered during export of TI collected from CrowdStrike as well as TI from MITRE. Error message shown: TypeError: can only concatenate str (not "Event") to str. Restarting the container results in the same error.

Replicated in OpenCTI version 5.2.3, but found also earlier (at least 5.0.2+). 

## Environment

1. OS (where OpenCTI server runs): Docker on CentOS8
2. OpenCTI version: 5.2.3
3. OpenCTI client: { e.g. frontend or python }
4. Other environment details: OpenCTI runs in Docker container. Containers used: opencti/connector-mitre:5.2.3, opencti/connector-splunk:5.2.3

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add opencti/connector-mitre:5.2.3
2. Add opencti/connector-splunk:5.2.3
3. Wait until MITRE connector downloads basic telemetry (see scope config below).
4. Set Splunk connector to export the telemetry to KV store in Splunk using live stream.
6. Error is shown in Splunk connector output.

## Actual Output
```INFO:root:[CREATE] Processing data {7845747d-bed4-427e-b29a-53f1f885926f}

INFO:root:Query post on /data/opencti

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): <REDACTED>

DEBUG:urllib3.connectionpool:https://<REDACTED> "POST /servicesNS/nobody/<REDACTED>/storage/collections/data/opencti HTTP/1.1" 201 47

Exception in thread Thread-2:

Traceback (most recent call last):

  File "/opt/opencti-connector-splunk/splunk.py", line 106, in _process_message

    data = json.loads(msg.data)["data"]

  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner

    self.run()

  File "/usr/local/lib/python3.9/site-packages/pycti/connector/opencti_connector_helper.py", line 382, in run

    self.callback(msg)

  File "/opt/opencti-connector-splunk/splunk.py", line 108, in _process_message

    raise ValueError("Cannot process the message: " + msg)

TypeError: can only concatenate str (not "Event") to str

DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti

DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 141

DEBUG:urllib3.connectionpool:Resetting dropped connection: opencti

DEBUG:urllib3.connectionpool:http://opencti:8080 "POST /graphql HTTP/1.1" 200 141

DEBUG:urllib3.connectionpool:Resetting dropped connection: ```
 
## Additional information

Splunk connector config:
      - CONNECTOR_TYPE=STREAM
      - CONNECTOR_LIVE_STREAM_ID=live
      - "CONNECTOR_NAME=Export to Splunk Connector"
      - CONNECTOR_SCOPE=elastic
      - CONNECTOR_CONFIDENCE_LEVEL=80
      - CONNECTOR_LOG_LEVEL=debug

MITRE connector config:
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - "CONNECTOR_NAME=MITRE ATT&CK"
      - CONNECTOR_SCOPE=marking-definition,identity,attack-pattern,course-of-action,intrusion-set
      - CONNECTOR_CONFIDENCE_LEVEL=15 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_MOBILE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/mobile-attack/mobile-attack.json
      - MITRE_ICS_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/ics-attack/ics-attack.json
      - MITRE_INTERVAL=7 # In days, must be strictly greater than 1

## Screenshots (optional)

**Comment by nor3th** [comment]
Hey @Vieteg 

Any chance you know what kind of events cause the issue?

Regards

**Comment by Vieteg** [comment]
I looked into it further. Looks like error is how urllib3 interprets error 409 from Splunk. With this return code Splunk claims there is already a record in Splunk KV store with the same key. I tested and it wasn't the case, Splunk just mishandles the query I guess. 

In any case, this isn't a bug in OpenCTI connector, so I am going to close this issue.
