### ISSUE TITLE
[Cryptolaemus Connector] Large number of HTTP 500 errors from data of the connector

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/connectors#670]
## Description

Seeing a large number of errors from the data of the Cryptolaemus connector. It seems it's consistently trying to create a Malware : Emotet but the malware already exists from first creation. 

## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: 5.2.4
3. OpenCTI client: Connector
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1.Start Cryptolaemus connector. 
2. Observe the OpenCTI logs and connector logs
3. Errors will start popping up at a very fast rate. 

## Expected Output

Ingestion of Cryptolaemus data

## Actual Output

Error in the logs
 
### Logs

Cryptolaemus Connector log snippet 

```
ERROR:root:Restricted entity already exists
ERROR:root:{'name': 'UnsupportedError', 'message': 'Restricted entity already exists'}
INFO:root:Connector last run: 2022-04-24 02:36:11
INFO:root:Connector will run!
INFO:root:Creating Identity {Cryptolaemus Team}.
INFO:root:Creating External Reference {Cryptolaemus Team's Emotet C2 update of 2021-01-25T23:59:00+00:00}.
INFO:root:Creating Malware {Emotet}.
ERROR:root:Restricted entity already exists
ERROR:root:{'name': 'UnsupportedError', 'message': 'Restricted entity already exists'}
```

OpenCTI Platform log snippet

```
{"category":"APP","error":{"data":{"category":"business","http_status":500,"reason":"Restricted entity already exists"},"stacktrace":["UnsupportedError: Unsupported operation","at error (/opt/opencti/build/src/config/errors.js:8:10)","at UnsupportedError (/opt/opencti/build/src/config/errors.js:62:51)","at createEntityRaw (/opt/opencti/build/src/database/middleware.js:2829:15)","at createEntity (/opt/opencti/build/src/database/middleware.js:2935:16)","at addMalware (/opt/opencti/build/src/domain/malware.js:23:19)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"MalwareAdd","operation_query":"mutation MalwareAdd($input:MalwareAddInput){malwareAdd(input:$input){id standard_id entity_type parent_types}}","size":729,"time":29,"timestamp":"2022-04-29T09:53:40.941Z","type":"WRITE_ERROR","user":{"ip":"::ffff:172.18.0.6","user_id":"f7f49582-dee2-4f91-ab35-59b88b7fc382"},"variables":{"input":{"aliases":null,"architecture_execution_envs":null,"capabilities":null,"confidence":null,"created":null,"createdBy":null,"description":"Emotet is a modular malware variant which is primarily used as a downloader for other malware variants such as TrickBot and IcedID. Emotet first emerged in June 2014 and has been primarily used to target the banking sector. (Citation: Trend Micro Banking Malware Jan 2019)","externalReferences":null,"first_seen":null,"implementation_languages":null,"is_family":null,"killChainPhases":null,"lang":null,"last_seen":null,"malware_types":null,"modified":null,"name":"Emotet","objectLabel":null,"objectMarking":null,"revoked":null,"stix_id":null,"update":false,"x_opencti_stix_ids":null}},"version":"5.2.4"}

    {"category":"APP","error":{"data":{"category":"business","http_status":500,"reason":"Restricted entity already exists"},"stacktrace":["UnsupportedError: Unsupported operation","at error (/opt/opencti/build/src/config/errors.js:8:10)","at UnsupportedError (/opt/opencti/build/src/config/errors.js:62:51)","at createEntityRaw (/opt/opencti/build/src/database/middleware.js:2829:15)","at createEntity (/opt/opencti/build/src/database/middleware.js:2935:16)","at addMalware (/opt/opencti/build/src/domain/malware.js:23:19)"]},"inner_relation_creation":0,"level":"error","message":"API Call","operation":"MalwareAdd","operation_query":"mutation MalwareAdd($input:MalwareAddInput){malwareAdd(input:$input){id standard_id entity_type parent_types}}","size":729,"time":38,"timestamp":"2022-04-29T09:54:46.881Z","type":"WRITE_ERROR","user":{"ip":"::ffff:172.18.0.6","user_id":"f7f49582-dee2-4f91-ab35-59b88b7fc382"},"variables":{"input":{"aliases":null,"architecture_execution_envs":null,"capabilities":null,"confidence":null,"created":null,"createdBy":null,"description":"Emotet is a modular malware variant which is primarily used as a downloader for other malware variants such as TrickBot and IcedID. Emotet first emerged in June 2014 and has been primarily used to target the banking sector. (Citation: Trend Micro Banking Malware Jan 2019)","externalReferences":null,"first_seen":null,"implementation_languages":null,"is_family":null,"killChainPhases":null,"lang":null,"last_seen":null,"malware_types":null,"modified":null,"name":"Emotet","objectLabel":null,"objectMarking":null,"revoked":null,"stix_id":null,"update":false,"x_opencti_stix_ids":null}},"version":"5.2.4"}
    {"auth":{"email":"malwarebazaar@cybernetis.tech","ip":"::ffff:172.18.0.21","user_id":"5c1e33d2-087a-4f68-8a4c-b802db48898b"},"category":"AUDIT","level":"info","message":"UPLOAD","resource":{"filename":"New order is attached.exe","metadata":{"entity_id":"f3131fbf-0e33-479f-bedd-5d89fbd5c590"},"path":"import/Artifact/f3131fbf-0e33-479f-bedd-5d89fbd5c590"},"timestamp":"2022-04-29T09:54:55.039Z","version":"5.2.4"}

    {"category":"APP","error":{"data":{"category":"business","http_status":500,"reason":"Restricted entity already exists"},"stacktrace":["UnsupportedError: Unsupported operation","at error (/opt/opencti/build/src/config/errors.js:8:10)","at UnsupportedError (/opt/opencti/build/src/config/errors.js:62:51)","at createEntityRaw (/opt/opencti/buil^Cd":null,"createdBy":null,"description":"Emotet is a modular malware variant which is primarily used as a downloader for other malware variants such as TrickBot and IcedID. Emotet first emerged in June 2014 and has been primarily used to target the banking sector. (Citation: Trend Micro Banking Malware Jan 2019)","externalReferences":null,"first_seen":null,"implementation_languages":null,"is_family":null,"killChainPhases":null,"lang":null,"last_seen":null,"malware_types":null,"modified":null,"name":"Emotet","objectLabel":null,"objectMarking":null,"revoked":null,"stix_id":null,"update":false,"x_opencti_stix_ids":null}},"version":"5.2.4"}
```

**Comment by SamuelHassine** [comment]
Hello @cvdsouza,

This error means your connector don't have enough permissions (in terms of TLP level) to create this:

Malware Emotet already exists, but the creator does not have the permission to read it, so it spawned an error "Restricted entity already exists".

Kind regards,
Samuel
