### ISSUE TITLE
connector-export-report-pdf - KeyError: 'entity_id'

### ISSUE THREAD

**Issue by SYNchroACK** [OpenCTI-Platform/connectors#696]
## Description

Selected 2 observables and tried to export them using connector export report pdf. I also tried to export selecting a report and it did not work too.

```
opencti-connector-export-report-pdf-1  | INFO:root:Reporting work update_received opencti-work--4a28afb7-7cc7-47a7-b6bf-6dd344f72f6c
opencti-connector-export-report-pdf-1  | ERROR:root:Error in message processing, reporting error to API
opencti-connector-export-report-pdf-1  | Traceback (most recent call last):
opencti-connector-export-report-pdf-1  |   File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 175, in _data_handler
opencti-connector-export-report-pdf-1  |     message = self.callback(json_data["event"])
opencti-connector-export-report-pdf-1  |   File "/opt/opencti-connector-export-report-pdf/export-report-pdf.py", line 97, in _process_message
opencti-connector-export-report-pdf-1  |     entity_id = data["entity_id"]
opencti-connector-export-report-pdf-1  | KeyError: 'entity_id'
opencti-connector-export-report-pdf-1  | INFO:root:Reporting work update_received opencti-work--4a28afb7-7cc7-47a7-b6bf-6dd344f72f6c
opencti-connector-export-report-pdf-1  | INFO:root:Message (delivery_tag=4) processed, thread terminated
```

```
    image: opencti/connector-export-report-pdf:5.3.1
    environment:
      - OPENCTI_URL=http://platform:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=${CONNECTOR_EXPORT_REPORT_FILE_ID} # Valid UUIDv4
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportReportPdf
      - CONNECTOR_SCOPE=application/pdf
      - CONNECTOR_CONFIDENCE_LEVEL=100 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - EXPORT_REPORT_PDF_PRIMARY_COLOR=#ff8c00 # The primary color for the output pdf
      - EXPORT_REPORT_PDF_SECONDARY_COLOR=#000000 # The secondary color for the output pdf
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_1=My Company # The first line of your company address
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_2=123 Main Street
      - EXPORT_REPORT_PDF_COMPANY_ADDRESS_LINE_3=Miami, FL 33101 USA
      - EXPORT_REPORT_PDF_COMPANY_PHONE_NUMBER=888.888.8888 # The phone number of your company
      - EXPORT_REPORT_PDF_COMPANY_EMAIL=reports@company.com # The email of your company
      - EXPORT_REPORT_PDF_COMPANY_WEBSITE=https://company.com # The website of your company
      - EXPORT_REPORT_PDF_INDICATORS_ONLY=false # Whether or not to only include Observables that are Indicators in the report
      - EXPORT_REPORT_PDF_DEFANG_URLS=true # Replace http in Url observables with hxxp
```

## Environment

OpenCTI version: 5.3.1 (docker images)

## Reproducible Steps

![image](https://user-images.githubusercontent.com/4184292/171197143-c4231c8d-e642-446a-8398-962617f4ce85.png)

**Comment by remrem29** [comment]
Can confirm - Having the same error "KeyError: 'entity_id' after using the "connector-export-report-pdf" connector

**Comment by infernuxmonster** [comment]
@SamuelHassine quick question - since the only way to filter exports is on the markings, how do you suppose we actually export reports as PDF? Been trying to get this to work but can't seem to find out how.

**Comment by Ken-Abruzzi** [comment]
@SamuelHassine 
Hello! Even if I export some reports, the connector also says "This Connector currently only handles direct export (single entity and no list) of the following entity types: "Report" and "Intrusion-Set".
