### ISSUE TITLE
Internal Enrichment Connector - Always listening to a new observable

### ISSUE THREAD

**Issue by mariodcosta** [OpenCTI-Platform/connectors#733]
Guys,

I need help, I am developing a new **Internal Enrichment connector** and it is working, however I have to run it manually and  I want to leave the connector always listening for a new observable to check it and to make changes accordingly with my code.

I explored some internal enrichments connectors code, but they are not equal.

Can I use only this , that is used on AbuseIPDB code:

```
# Start the main loop
def start(self):
        self.helper.listen(self._process_message)
```

Thank you very much!!

**Comment by mariodcosta** [comment]
I developed the connector and when I run the container in the docker , config file is read well, however the code stop because of this error:
`Successfully built f3ca9d203585
[root@ip-10-0-0-181 osthreatenrichment]# docker run f3ca9d203585
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: ac14462d-7d36-4da9-96c9-51e8bbb089c4
INFO:root:Starting ping alive thread
INFO:root:Creating Identity {OsThreatEnrichment}.
ERROR:pika.adapters.utils.selector_ioloop_adapter:Address resolution failed: gaierror(-2, 'Name does not resolve')
ERROR:pika.adapters.utils.connection_workflow:getaddrinfo failed: gaierror(-2, 'Name does not resolve').
ERROR:pika.adapters.utils.connection_workflow:AMQP connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None.
ERROR:pika.adapters.utils.connection_workflow:AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
ERROR:pika.adapters.blocking_connection:Connection workflow failed: AMQPConnectionWorkflowFailed: 1 exceptions in all; last exception - gaierror(-2, 'Name does not resolve'); first exception - None
ERROR:pika.adapters.blocking_connection:Error in _create_connection().
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
  File "/usr/local/lib/python3.10/site-packages/pika/adapters/utils/selector_ioloop_adapter.py", line 565, in _resolve
    result = socket.getaddrinfo(self._host, self._port, self._family,
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
ERROR:root:[Errno -2] Name does not resolve`
