### ISSUE TITLE
[Intezer Connector] Error in message processing

### ISSUE THREAD

**Issue by fugitive101** [OpenCTI-Platform/connectors#738]
## Description

The bug is present when using the Intezer connector. There is an error raised - see  log:

`Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 118, in _process_file

    raise ValueError(f"No files found for {observable['observable_value']}")

ValueError: No files found for 475835b6703aade008c297f726c4cbe8fe29ac4d67bcf28d3761aeab59d3e929

INFO:root:Reporting work update_received opencti-work--5fb6c917-1b18-4870-9f9b-a8961f1661d2

INFO:root:Message (delivery_tag=43) processed, thread terminated

INFO:root:Reporting work update_received opencti-work--ec7a2988-8df2-4f3a-8d7c-1802b18fdf01

INFO:root:Reading StixCyberObservable {8d79573b-0720-40b8-b92b-89b58fb64a6f}.

INFO:root:Processing the observable d486d807f4e11918a935df4673c32731fb292a8fa77158741aee2a16fb5b298f

ERROR:root:Error in message processing, reporting error to API

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 127, in _process_file

    result_url = self.intezer_client.upload_file(

  File "/opt/opencti-connector-intezer-sandbox/intezer_api.py", line 39, in upload_file

    assert response.status_code == 201

AssertionError

INFO:root:Reporting work update_received opencti-work--ec7a2988-8df2-4f3a-8d7c-1802b18fdf01

INFO:root:Message (delivery_tag=44) processed, thread terminated

INFO:root:Reporting work update_received opencti-work--0acea19e-6b8b-4602-a713-92476294c4d5

INFO:root:Reading StixCyberObservable {0e37c49b-6ae5-49b8-b984-26284e308604}.

INFO:root:Processing the observable 2a42f058cb8189ad5133b20a42dc23de418e6107926243132264a8d44d3f32f2

ERROR:root:Error in message processing, reporting error to API

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 118, in _process_file

    raise ValueError(f"No files found for {observable['observable_value']}")

ValueError: No files found for 2a42f058cb8189ad5133b20a42dc23de418e6107926243132264a8d44d3f32f2

INFO:root:Reporting work update_received opencti-work--0acea19e-6b8b-4602-a713-92476294c4d5

INFO:root:Message (delivery_tag=45) processed, thread terminated

INFO:root:Reporting work update_received opencti-work--04f265d8-a9f0-4750-b2a7-319d0b97fea6

INFO:root:Reading StixCyberObservable {6e44f30d-dab5-41af-86cc-dc4cf45616b6}.

INFO:root:Processing the observable d1a998486349214703d5aa3c13fe200e1098e5d0c8cf73561275e8211026a15c

ERROR:root:Error in message processing, reporting error to API

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 127, in _process_file

    result_url = self.intezer_client.upload_file(

  File "/opt/opencti-connector-intezer-sandbox/intezer_api.py", line 39, in upload_file

    assert response.status_code == 201

AssertionError

INFO:root:Reporting work update_received opencti-work--04f265d8-a9f0-4750-b2a7-319d0b97fea6

INFO:root:Message (delivery_tag=46) processed, thread terminated

INFO:root:Reporting work update_received opencti-work--6dbfdccc-597a-45d8-827d-4e571ec1ac0b

INFO:root:Reading StixCyberObservable {668236c5-7957-485a-9b9a-24354812be89}.

INFO:root:Processing the observable 09681462d42abbc451fc6d3b27d68a67dec8f999a17da7cc422b5240a4ee487a

ERROR:root:Error in message processing, reporting error to API

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 127, in _process_file

    result_url = self.intezer_client.upload_file(

  File "/opt/opencti-connector-intezer-sandbox/intezer_api.py", line 39, in upload_file

    assert response.status_code == 201

AssertionError

INFO:root:Reporting work update_received opencti-work--6dbfdccc-597a-45d8-827d-4e571ec1ac0b

INFO:root:Message (delivery_tag=47) processed, thread terminated

INFO:root:Reporting work update_received opencti-work--229fa15e-909a-4b82-a38e-937ae9de5a73

INFO:root:Reading StixCyberObservable {49e5ef94-ae0b-49f9-bf64-03c184d2ee43}.

INFO:root:Processing the observable 8cb5d6867d8460fbba1b3cf83e5ab95d22b9302f399b5094d20cb66565c240dd

ERROR:root:Error in message processing, reporting error to API

Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 178, in _data_handler

    message = self.callback(json_data["event"])

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 183, in _process_message

    return self._process_observable(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 160, in _process_observable

    return self._process_file(observable)

  File "/opt/opencti-connector-intezer-sandbox/intezer_sandbox.py", line 127, in _process_file

    result_url = self.intezer_client.upload_file(

  File "/opt/opencti-connector-intezer-sandbox/intezer_api.py", line 39, in upload_file

    assert response.status_code == 201

AssertionError

INFO:root:Reporting work update_received opencti-work--229fa15e-909a-4b82-a38e-937ae9de5a73`

## Environment

1. Ubuntu 20.04
2. OpenCTI version: 5.3.7

## Reproducible Steps
Install openCTI
Add Intezer connectorr

## Expected Output

Data enrichment.

**Comment by SamuelHassine** [comment]
@YungBinary Any idea about this one? Thanks a lot!

**Comment by YungBinary** [comment]
@SamuelHassine It looks like the assertion is failing and the response status code is not 201. This may have changed in the API. See https://github.com/OpenCTI-Platform/connectors/blob/14c9e0670c170dd1da912e11974b2401cd8db2b5/internal-enrichment/intezer-sandbox/src/intezer_api.py#L39

I'll play around with it when I get a chance to see what's going on.

**Comment by YungBinary** [comment]
@fugitive101 Do you have an API key setup? According to the documentation, 201 response is returned upon success (https://analyze.intezer.com/api-docs.html#/paths/analyze/post). You may be getting a 403 response which indicates you don't have authorization to call the API.

**Comment by YungBinary** [comment]
I was just able to reproduce this issue, diving deeper.

**Comment by YungBinary** [comment]
@SamuelHassine I added the fix to this in my latest PR please let me know if you want me to open a different PR for this as I can't fork the repo two times at once? https://github.com/OpenCTI-Platform/connectors/pull/861
