### ISSUE TITLE
Elastic Security connector not working.

### ISSUE THREAD

**Issue by bakhtawarw** [OpenCTI-Platform/connectors#839]
## Environment

1. OS (where OpenCTI server runs): Ubuntu 20.04
2. OpenCTI version: { e.g. OpenCTI 5.3.12 }
3. Elastic Security version: 7.15.0
4. OpenCTI environment: Docker
5. OpenCTI and Elastic Security are running on two separate ubuntu vms.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Added elastic connector in OpenCTI's docker compose file
2. Connector is fed config.yml in docker compose file
3. I am using  Elastic CertUtil Self signed certs, and have linked them into the config.yml
4. Connector is showing following error:
 

...........................................................................................

[2022-09-20T05:32:24.311][INFO] Using default data directory: /runtime/lib/python3.9/site-packages/elastic/data
[2022-09-20T05:32:25.215][INFO] Connected to OpenCTI
/runtime/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py:209: UserWarning: Connecting to https://10.0.2.14:9200 using SSL with verify_certs=False is insecure.
  warnings.warn(
[2022-09-20T05:32:25.297][INFO] Connected to Elasticsearch
[2022-09-20T05:32:25.303][INFO] Setting up Elasticsearch for OpenCTI Connector
[2022-09-20T05:32:25.393][WARNING] GET https://10.0.2.14:9200/_ilm/policy/opencti [status:404 request:0.005s]
[2022-09-20T05:32:25.394][WARNING] HTTP 404: Lifecycle policy not found: opencti
[2022-09-20T05:32:25.394][INFO] Creating ILM policy opencti
[2022-09-20T05:32:25.629][INFO] Installing index template: opencti
[2022-09-20T05:32:25.896][INFO] Parsing index pattern: opencti-{now/d}-000001
[2022-09-20T05:32:25.897][INFO] Initial index: <opencti-{now/d}-000001>
Alias: opencti
[2022-09-20T05:32:25.903][INFO] Creating alias 'opencti' to pattern '<opencti-{now/d}-000001>'
[2022-09-20T05:32:26.795][INFO] Initial index <opencti-{now/d}-000001> created.
Traceback (most recent call last):
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 73, in traverse
    value = value[key]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/runtime/bin/elastic", line 8, in <module>
    sys.exit(main())
  File "/runtime/lib/python3.9/site-packages/elastic/console.py", line 222, in main
    ElasticInstance = ElasticConnector(config=config, datadir=datadir)
  File "/runtime/lib/python3.9/site-packages/elastic/elastic.py", line 54, in __init__
    self.sightings_manager = SignalsManager(
  File "/runtime/lib/python3.9/site-packages/elastic/sightings_manager.py", line 49, in __init__
    _interval: str = self.config.get("elastic.signals.query_interval", "5m")
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 199, in get
    return self[path]
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 142, in __getitem__
    item = traverse(data=self.data, keys=keys, original_path=path)
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 79, in traverse
    raise type_error(key, original_path, value)
  File "/runtime/lib/python3.9/site-packages/scalpl/scalpl.py", line 37, in type_error
    raise TypeError(
TypeError: Cannot access key 'signals' in path 'elastic.signals.query_interval': the element must be a dictionary or a list but is of type '<class 'NoneType'>'.

................................................................................................

##Expected Ouput

Opencti index pattern showing data in Kibana's Discover Tab and creating rules and alerts based on that data in Elastic Security.

## Actual Output
The opencti index pattern just shows the following in Kibana's discover tab and elastic security is empty.
![image](https://user-images.githubusercontent.com/104062347/191180475-fe97af58-3ef9-48ed-a2ca-57fb853cb412.png)

 
## Additional information

**Docker-Compose file:**
connector-elastic:
    image: opencti/connector-elastic:5.3.12
    volumes:
      - ./certs:/app/certs
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=${OPENCTI_ADMIN_TOKEN}
      - CONNECTOR_ID=0de31b60-294d-4a9d-8f91-9c4b259dec34
      - CONNECTOR_TYPE=STREAM
      - CONNECTOR_LIVE_STREAM_ID=cb1903aa-534b-474a-a811-8484 # ID of the live stream created in the OpenCTI UI
      - CONNECTOR_LIVE_STREAM_LISTEN_DELETE=true
      - CONNECTOR_LIVE_STREAM_WITH_INFERENCES=false
      - CONNECTOR_LIVE_STREAM_NO_DEPENDENCIES=true
      - "CONNECTOR_NAME=OpenCTI Elastic Connector"
      - CONNECTOR_SCOPE=elastic
      - CONNECTOR_CONFIDENCE_LEVEL=80 # From 0 (Unknown) to 100 (Fully trusted)
      - CONNECTOR_LOG_LEVEL=info
      - "CONNECTOR_ENTITY_NAME=Elastic Detection Cluster"
      - "CONNECTOR_ENTITY_DESCRIPTION=Elasticsearch detection engine cluster"
      - CONNECTOR_MODE=ecs # Options
    restart: always
    depends_on:
      - opencti
    command:
      --config=/app/certs/config.yml
volumes:
    certs:
    external: true

**Config.yml**

opencti:
  url: 'http://10.0.2.16:8080'
  token: '90dc6acf-05f5-43dc-8981-c0c13e1d85fb'
  ssl_verify: False

connector:
  id: '0de31b60-294d-4a9d-8f91-9c4b259dec34'
  type: 'STREAM'
  name: 'OpenCTI Elastic Connector'
  scope: 'elastic'
  confidence_level: 80 # From 0 (Unknown) to 100 (Fully trusted). Used for Sightings reported to OpenCTI
  log_level: 'info'
  entity_name: 'Elastic Detection Cluster'
  entity_description: 'Elasticsearch detection engine cluster'
  live_stream_id: 'cb1903aa-534b-474a-a811-8484'
  live_stream_listen_delete: true
  start_timestamp: '1655890657402' ### format example Wed, 22 Jun 2022 09:46:24 GMT
  mode: ecs # Options are 'ecs' (indicators only) or 'stix' (raw STIX documents)

# =============================== Elastic Cloud ================================
# The cloud.id setting overwrites the `elastic.hosts`
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:
# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
# API key is recommended
#cloud.auth:

output.elasticsearch:
  # ---------------------------- Elasticsearch Output ----------------------------
  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify an additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: ["https://10.0.2.14:9200"]
  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "changeme"
  ssl_verify: false
  ssl.certificate_authorities: ["/app/certs/elasticsearch-ca.pem"]
  ssl.certificate: "/app/certs/ca.crt"
  ssl.key: "/app/certs/ca.key"

  # Optional index name. The default is "opencti" plus the date. Uses Elastic date math syntax.
  # Custom index settings are ignored when ILM is enabled.  Be sure to update
  # `setup.template.pattern` if you change the output index.
  #index: "opencti-{now/d}"

# ====================== Index Lifecycle Management (ILM) ======================

# Configure index lifecycle management (ILM). These settings create a write
# alias and add additional settings to the index template. When ILM is enabled,
# output.elasticsearch.index is ignored, and the write alias is used to set the
# index name.
setup:
  ilm:
    enabled: True
    policy_name: opencti
    rollover_alias: opencti
    # This pattern uses datemath. See https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html
    pattern: "{now/d}-000001"
    overwrite: True
  template:
    enabled: True
    name: opencti
    # This pattern value is used when applying the template, but also used when applying
    # document updates. Make sure this matches the output indices in all cases.
    pattern: opencti-*
    overwrite: True

elastic:
  # ---------------------------- Sightings Settings ----------------------------

  # (optional) This is to fine tune how we find signals generated by the detection engine
  # These are all the defaults, you don't need to change anything or even include it.
  # You could modify the query if you wanted to add some additional criteria.
  # You could also change the signal_index pattern if you had a non-default space in
  # Kibana that you wanted to use to limit the results
  signals:
     query_interval: '5m'
     lookback_interval: '5m'
     signal_index: '.siem-signals-*'
     query: >
       {
        "query": {
           "bool": {
           "must": {
               "match": { "signal.rule.type": "threat_match" }
             }
          }
        }
       }
  # (optional) TLP to use when importing sightings from Elastic, defaults to empty
  #sightings_tlp:

##Screenshots

I can see the opencti index , template and index lifecycle policies.

![Uploading image.png…]()

**Comment by dcode** [comment]
@bakhtawarw , is your actual `config.yml` indented? Can you edit your posted files above as code blocks? Use ` ``` ` to delimit the top and bottom or use the formatting buttons of the text box. 

The error specifically is concerned with being unable to access `elastic.signals`. The relevant section of the config file _should_ look similar to this (2 spaces per block indent):

```yaml
elastic:
  signals:
      query_interval: '5m'
```

**Comment by bakhtawarw** [comment]
@dcode  now I'm getting the following error.
![image](https://user-images.githubusercontent.com/104062347/191889541-f8e36ea3-93bf-444c-9b3e-e487f143c5c4.png)

Live Stream is as follows:
![image](https://user-images.githubusercontent.com/104062347/191889590-a3d3c7e5-499d-433d-80e9-9b1324b1900b.png)


Docker-Compose file
![image](https://user-images.githubusercontent.com/104062347/191889640-d32ac1b1-e40d-46c3-882d-b385ef9813f2.png)


and Config.yml

opencti:
  url: 'http://10.0.2.9:8080'
  token: '462d3d84-bb96-459d-ab86-d6128515a6f8'
  ssl_verify: False

connector:
  id: 'ef5d41e1-f09c-4222-8fe8-59fd4dce1ee8'
  type: 'STREAM'
  name: 'OpenCTI Elastic Connector'
  scope: 'elastic'
  confidence_level: 80 # From 0 (Unknown) to 100 (Fully trusted). Used for Sightings reported to OpenCTI
  log_level: 'info'
  entity_name: 'Elastic Detection Cluster'
  entity_description: 'Elasticsearch detection engine cluster'
  live_stream_id: '8b69accf-dd30-49ba-be29-eac5bd8333a7E'
  live_stream_listen_delete: true
  start_timestamp: '1655890657402' ### format example Wed, 22 Jun 2022 09:46:24 GMT
  mode: ecs # Options are 'ecs' (indicators only) or 'stix' (raw STIX documents)

# =============================== Elastic Cloud ================================
# The cloud.id setting overwrites the `elastic.hosts`
# You can find the `cloud.id` in the Elastic Cloud web UI.
#cloud.id:
# The cloud.auth setting overwrites the `output.elasticsearch.username` and
# `output.elasticsearch.password` settings. The format is `<user>:<pass>`.
# API key is recommended
#cloud.auth:

output.elasticsearch:
  # ---------------------------- Elasticsearch Output ----------------------------
  # Array of hosts to connect to.
  # Scheme and port can be left out and will be set to the default (http and 9200)
  # In case you specify an additional path, the scheme is required: http://localhost:9200/path
  # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
  hosts: ["https://10.0.2.10:9200"]
  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elastic"
  password: "changeme"
  ssl_verify: false
  ssl.certificate_authorities: ["/app/certs/elasticsearch-ca.pem"]
  ssl.certificate: "/app/certs/ca.crt"
  ssl.key: "/app/certs/ca.key"
  # Optional index name. The default is "opencti" plus the date. Uses Elastic date math syntax.
  # Custom index settings are ignored when ILM is enabled.  Be sure to update
  # `setup.template.pattern` if you change the output index.
  #index: "opencti-{now/d}"

# ====================== Index Lifecycle Management (ILM) ======================

# Configure index lifecycle management (ILM). These settings create a write
# alias and add additional settings to the index template. When ILM is enabled,
# output.elasticsearch.index is ignored, and the write alias is used to set the
# index name.
setup:
  ilm:
    enabled: True
    policy_name: opencti
    rollover_alias: opencti
    # This pattern uses datemath. See https://www.elastic.co/guide/en/beats/filebeat/current/ilm.html
    pattern: "{now/d}-000001"
    overwrite: False
  template:
    enabled: True
    name: opencti
    # This pattern value is used when applying the template, but also used when applying
    # document updates. Make sure this matches the output indices in all cases.
    pattern: opencti-*
    overwrite: False

elastic:
  # ---------------------------- Sightings Settings ----------------------------

  # (optional) This is to fine tune how we find signals generated by the detection engine
  # These are all the defaults, you don't need to change anything or even include it.
  # You could modify the query if you wanted to add some additional criteria.
  # You could also change the signal_index pattern if you had a non-default space in
  # Kibana that you wanted to use to limit the results
   signals:
     query_interval: '5m'
     lookback_interval: '5m'
     signal_index: '.siem-signals-*'
     query: >
       {
         "query": {
           "bool": {
             "must": {
               "match": { "signal.rule.type": "threat_match" }
             }
           }
         }
       }
  # (optional) TLP to use when importing sightings from Elastic, defaults to empty
  #sightings_tlp:
  # (optional) TLP to use when importing sightings from Elastic, defaults to empty
  #sightings_tlp:
