### ISSUE TITLE
Malpedia : Technical error > Cannot read property '

### ISSUE THREAD

**Issue by cvdsouza** [OpenCTI-Platform/connectors#85]
## Description

Installed the malpedia connector using the release v3.1.0. Seeing openCTI output errors in the logs. Also seeing the same errors on the malpedia connector side

## Environment

1. OS (where OpenCTI server runs): Ubuntu 18.04 ( Manual Installation of OpenCTI)
2. OpenCTI version: 3.1.0
3. OpenCTI client: python connector
4. Other environment details:
Manual installation of OpenCTI and connectors. 
## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. cd malpedia/src
2. cp config.yaml.sample config.yaml
3. pip3 install -r requirements.txt
4. python3 malpedia.py

## Expected Output
On the front end I see only one yara rule from malpedia. Seems after that error, nothing else is getting ingested. Give the details in malpedia i.e. yara rule size, I would expect to see more. 

## Actual Output
 
**malpedia Log**
```
INFO:root:Creating stix_relation {indicator: fe23dcf2-368b-42fc-8fde-94aa0e901d23, characterize: b789bf8c-101b-4542-91c5-fbcf128bd522}.
INFO:root:{"errors":[{"message":"An unknown error has occurred!  Please try again later.","name":"Unknown","time_thrown":"2020-04-10T13:00:37.682Z","data":{"type":"technical","level":"error"}}]}

ERROR:root:'NoneType' object is not subscriptable
```

**OpenCTI Log**

```
{"level":"error","message":"[GRAKN] executeWrite error > Cannot read property 'description' of null","stack":"TypeError: Cannot read property 'description' of null\n    at Ce (/opt/opencti/opencti/build/index.js:1:31551)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async R (/opt/opencti/opencti/build/index.js:1:4536)"}
{"message":"[OPENCTI] Technical error > Cannot read property 'description' of null","locations":[{"line":4,"column":25}],"path":["stixObservableRelationEdit","fieldPatch"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'description' of null","    at Ce (/opt/opencti/opencti/build/index.js:1:31551)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async R (/opt/opencti/opencti/build/index.js:1:4536)"]}},"level":"error"}
{"message":"[OPENCTI] Technical error > Variable \"$input\" got invalid value { id: \"9c46de92-b6d2-4fca-9806-39beb3d9bbd1\", stix_id_key: \"identity--c2f4cb5d-ceff-4cd9-a4e3-d5c24af3117e\", entity_type: \"organization\", parent_types: [\"Organization\", \"Identity\", \"Stix-Domain-Entity\", \"Stix-Domain\"], name: \"Malpedia\", alias: [], description: \"Malpedia is a free service offered by Fraunhofer FKIE.\", graph_data: null, created_at: \"2020-04-09T22:39:59.853Z\", updated_at: \"2020-04-09T22:39:59.853Z\", createdByRef: null, markingDefinitions: [], tags: [], externalReferences: [], importFiles: [], organization_class: null, markingDefinitionsIds: [], tagsIds: [], externalReferencesIds: [], importFilesIds: [] } at \"input.createdByRef\"; Expected type String. String cannot represent a non string value: { id: \"9c46de92-b6d2-4fca-9806-39beb3d9bbd1\", stix_id_key: \"identity--c2f4cb5d-ceff-4cd9-a4e3-d5c24af3117e\", entity_type: \"organization\", parent_types: [\"Organization\", \"Identity\", \"Stix-Domain-Entity\", \"Stix-Domain\"], name: \"Malpedia\", alias: [], description: \"Malpedia is a free service offered by Fraunhofer FKIE.\", graph_data: null, created_at: \"2020-04-09T22:39:59.853Z\", updated_at: \"2020-04-09T22:39:59.853Z\", createdByRef: null, markingDefinitions: [], tags: [], externalReferences: [], importFiles: [], organization_class: null, markingDefinitionsIds: [], tagsIds: [], externalReferencesIds: [], importFilesIds: [] }","locations":[{"line":2,"column":50}],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: String cannot represent a non string value: { id: \"9c46de92-b6d2-4fca-9806-39beb3d9bbd1\", stix_id_key: \"identity--c2f4cb5d-ceff-4cd9-a4e3-d5c24af3117e\", entity_type: \"organization\", parent_types: [\"Organization\", \"Identity\", \"Stix-Domain-Entity\", \"Stix-Domain\"], name: \"Malpedia\", alias: [], description: \"Malpedia is a free service offered by Fraunhofer FKIE.\", graph_data: null, created_at: \"2020-04-09T22:39:59.853Z\", updated_at: \"2020-04-09T22:39:59.853Z\", createdByRef: null, markingDefinitions: [], tags: [], externalReferences: [], importFiles: [], organization_class: null, markingDefinitionsIds: [], tagsIds: [], externalReferencesIds: [], importFilesIds: [] }","    at GraphQLScalarType.coerceString [as parseValue] (/opt/opencti/opencti/node_modules/graphql/type/scalars.js:164:11)","    at coerceInputValueImpl (/opt/opencti/opencti/node_modules/graphql/utilities/coerceInputValue.js:127:26)","    at coerceInputValueImpl (/opt/opencti/opencti/node_modules/graphql/utilities/coerceInputValue.js:105:35)","    at coerceInputValueImpl (/opt/opencti/opencti/node_modules/graphql/utilities/coerceInputValue.js:54:14)","    at coerceInputValue (/opt/opencti/opencti/node_modules/graphql/utilities/coerceInputValue.js:37:10)","    at _loop (/opt/opencti/opencti/node_modules/graphql/execution/values.js:107:69)","    at coerceVariableValues (/opt/opencti/opencti/node_modules/graphql/execution/values.js:119:16)","    at getVariableValues (/opt/opencti/opencti/node_modules/graphql/execution/values.js:48:19)","    at buildExecutionContext (/opt/opencti/opencti/node_modules/graphql/execution/execute.js:184:61)","    at executeImpl (/opt/opencti/opencti/node_modules/graphql/execution/execute.js:89:20)","    at Object.execute (/opt/opencti/opencti/node_modules/graphql/execution/execute.js:64:35)","    at /opt/opencti/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:246:46","    at Generator.next (<anonymous>)","    at /opt/opencti/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:8:71","    at new Promise (<anonymous>)","    at __awaiter (/opt/opencti/opencti/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)"]}},"level":"error"}
```

**Comment by SamuelHassine** [comment]
@rhaist is currently working on the Malpedia connector (#49), so the connector is currently not ready for production. Please re-open this issue once the connector will be officially released in the [OpenCTI ecosystem](https://www.notion.so/luatix/OpenCTI-Ecosystem-868329e9fb734fca89692b2ed6087e76).

**Comment by cvdsouza** [comment]
PUlled the updated connector, and it's pulling in data. Thanks for the update.
