### ISSUE TITLE
AlienVault API version

### ISSUE THREAD

**Issue by 0xalpaca** [OpenCTI-Platform/connectors#883]
## Description
While debugging my AlienVault connector installation, I found that the API v1 has some connection problems. I resolve this problem by using the API v2.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.04.1 LTS
2. OpenCTI version: OpenCTI 5.3.17
3. OpenCTI client: frontend
4. Other environment details: the OpenCTI server is behind a proxy

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. OpenCTI is deployed with the AlienVault connector by using **docker-compose**
2. `docker logs [container ID]`
3. Error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 178, in get
    response = self.session().get(
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='otx.alienvault.com', port=443): Max retries exceeded with url: /api/v1/pulses/subscribed?limit=20&modified_since=2020-05-01T00%3A00%3A00 (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/opencti-connector-alienvault/main.py", line 8, in <module>
    connector.run()
  File "/opt/opencti-connector-alienvault/alienvault/core.py", line 255, in run
    pulse_import_state = self.pulse_importer.run(current_state, work_id)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 100, in run
    pulses = self._fetch_subscribed_pulses(latest_pulse_datetime)
  File "/opt/opencti-connector-alienvault/alienvault/importer.py", line 191, in _fetch_subscribed_pulses
    pulses = self.client.get_pulses_subscribed(modified_since)
  File "/opt/opencti-connector-alienvault/alienvault/client.py", line 40, in get_pulses_subscribed
    pulse_data = self.otx.getsince(timestamp=modified_since, limit=limit)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 431, in getsince
    return self.getall(limit=limit, modified_since=timestamp, max_page=max_page, max_items=max_items, iter=False)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 404, in getall
    return self.walkapi(
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 385, in walkapi
    return list(self.walkapi_iter(url, max_page=max_page, max_items=max_items, method=method, body=body))
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 366, in walkapi_iter
    data = self.get(next_page_url)
  File "/usr/local/lib/python3.10/site-packages/OTXv2.py", line 187, in get
    raise RetryError()
OTXv2.RetryError: 'Exceeded maximum number of retries'
Killed
INFO:root:Listing Threat-Actors with filters null.
INFO:root:Connector registered with ID: 46f004c5-dff1-42de-9e3c-6456e48ef326
INFO:root:Starting ping alive thread
INFO:root:Starting AlienVault connector...
INFO:root:Running AlienVault connector...
INFO:root:Loaded state: {}
INFO:root:Connector first run
INFO:root:Initiate work for 46f004c5-dff1-42de-9e3c-6456e48ef326
INFO:root:Running pulse importer (update data: False, guess malware: False, guess cve: False, relationships: True, patterns_indicates: True, filter_indicators: True)...
INFO:root:Fetching subscribed pulses...
```

## Expected Output

Ingest data from OTX

## Actual Output

Doesn't ingest data from OTX
 
## Additional information

1. In order to debug, I've used `curl` command:
`curl https://otx.alienvault.com/api/v1/pulses/subscribed?page=1 -H "X-OTX-API-KEY:[REDACTED]" -v`

Response:
```
* Uses proxy env variable https_proxy == 'http://proxy:8080'
*   Trying proxy:8080...
* Connected to proxy port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to otx.alienvault.com:443
> CONNECT otx.alienvault.com:443 HTTP/1.1
> Host: otx.alienvault.com:443
> User-Agent: curl/7.81.0
> Proxy-Connection: Keep-Alive
>
< HTTP/1.1 200 Connection established
< Proxy-Agent: Proxy/1.0
<
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS header, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=otx.alienvault.io
*  start date: Apr 19 00:00:00 2022 GMT
*  expire date: May 18 23:59:59 2023 GMT
*  subjectAltName: host "otx.alienvault.com" matched cert's "otx.alienvault.com"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
* TLSv1.2 (OUT), TLS header, Supplemental data (23):
> GET /api/v1/pulses/subscribed?page=1 HTTP/1.1
> Host: otx.alienvault.com
> User-Agent: curl/7.81.0
> Accept: */*
> X-OTX-API-KEY: [REDACTED]
>
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* Mark bundle as not supporting multiuse
< HTTP/1.1 504 Gateway Time-out
< Content-Type: text/html
< Content-Length: 132
< Connection: keep-alive
< Server: awselb/2.0
< Date: Thu, 27 Oct 2022 09:00:39 GMT
< X-Cache: Error from cloudfront
< Via: 1.1 a8f77777c0752dad31367fbd24424a90.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: LHR62-C5
< X-Amz-Cf-Id: cNnTISD74adgpaHl6pUjZxf6rxd1Fgg_msPov4Ix8ZsTxcshh3lHbQ==
<
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
* Connection #0 to host 10.0.10.4 left intact
```

2. It works by using the v2 API:
` curl https://otx.alienvault.com/api/v2/pulses/subscribed?page=1 -H "X-OTX-API-KEY: [REDACTED]" -v`

```
[...]
< HTTP/1.1 200 OK
< Content-Type: text/html
< Content-Length: 8510
< Connection: keep-alive
< Server: CloudFront
[...]
```

**Comment by 0xalpaca** [comment]
False positive. I've tried to delete the issue but impossible from my side
