### ISSUE TITLE
STIX Connector not importing all data / breaking import page on 5.5.3

### ISSUE THREAD

**Issue by ckane** [OpenCTI-Platform/connectors#941]
## Description

I'm trying to upload a STIX JSON file (v2.1) that contains Indicators, SHA-256 File observables, and relationships between them all. However, the Workbench doesn't display any of the SHA-256 hashes, and only the indicators, and an attempt to upload fails. In 5.5.3, the upload causes the "Import data and analyst workbenches" page to cease to render properly (see error below) after it was uploaded.

## Environment

1. OS (where OpenCTI server runs): Ubuntu 22.10
2. OpenCTI version: OpenCTI 5.4.0, 5.5.3
3. OpenCTI client: 5.4.0, 5.5.3
4. Other environment details: Single EC2 instance, not using containers

## Reproducible Steps

Steps to create the smallest reproducible scenario:

The following file contains the STIX 2.1 bundle I'm trying to upload:
[mustang_hashes.json.txt](https://github.com/OpenCTI-Platform/connectors/files/10145536/mustang_hashes.json.txt)

Go into an Analysis report, go to it's "Data" tab, Click the "Select Your File" icon next to the "Uploaded Files" header.
![image](https://user-images.githubusercontent.com/3454769/205420703-ea88720f-5848-41f8-a276-29eccd2605c7.png)

Once uploaded, click the "Launch an Import of this File" next to the new file row, select ImportStixFile from the dialog - wait for it to import. Once complete, a new row displays in the "Analyst Workbenches" to the right, click that row and it will open up the relevant workbench.

Once there, I get a list of indicators but nothing in observables:
![image](https://user-images.githubusercontent.com/3454769/205420757-e2e0988a-7caa-4ed6-a50e-0fe47124308a.png)

Visiting the relationships tab shows the relationships are extracted, but right-hand-side (observable side) is "unknown" for all:
![image](https://user-images.githubusercontent.com/3454769/205420776-da9d2a69-1a35-4f13-8ba7-54de7904caaa.png)

## Expected Output

Have corresponding Observables to my Indicators and relationships

## Actual Output

Only have Indicators and Half-defined relationships, but no observables

**Comment by ckane** [comment]
I retried this import using the "Data import and analyst workbenches" UI page on 5.5.3 and after uploading the above-linked `mustang_hashes.json` file, the page will no longer render:
![image](https://user-images.githubusercontent.com/3454769/217330235-8719c58c-e781-4517-abed-73af4f2aecc4.png)

Refreshing the page doesn't help, and it just leads to the above error. There was only one PDF in the "workbenches" queue when I uploaded the JSON STIX file.

**Comment by SamuelHassine** [comment]
Hello @ckane,

I've tried to upload the file in the demo and it's working:  https://demo.opencti.io/dashboard/import/pending/aW1wb3J0L3BlbmRpbmcvbXVzdGFuZ19oYXNoZXMuanNvbg==.

Can you please copy/paste the error you have in the console log of the browser? If any, also the logs on the platform side.

Kind regards,
Samuel

**Comment by ckane** [comment]
New issue tracked in https://github.com/OpenCTI-Platform/opencti/issues/2825... will validate original issue when that's completed.

**Comment by ckane** [comment]
So, I've tried this again on 5.5.4, and it produces the following errors:
```
pencti-docker-connector-import-file-stix-1  | Error: unable to import required numpy module.
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:36:20.731360Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
opencti-docker-connector-import-file-stix-1  | See https://pypi.python.org/pypi/numpy.OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:36:37.204630Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
opencti-docker-connector-import-file-stix-1  | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:36:53.988292Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
opencti-docker-connector-import-file-stix-1  | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:37:07.594911Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:37:08.169360Z", "level": "INFO", "name": "pycti.entities", "message": "Listing Threat-Actors with filters null."}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:37:08.818522Z", "level": "INFO", "name": "pycti.connector", "message": "Connector registered with ID: 72327164-0b35-482b-b5d6-a5a3f76b845f"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:37:08.819000Z", "level": "INFO", "name": "pycti.connector", "message": "Starting ping alive thread"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:39:08.223137Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-09T00:39:07.580Z"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:39:09.195522Z", "level": "INFO", "name": "pycti.connector", "message": "Importing the file http://opencti:8080/storage/get/import/global/mustang_hashes.json"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:39:09.526911Z", "level": "INFO", "name": "pycti.api", "message": "Uploading a file."}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:39:10.196191Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-09T00:39:07.580Z"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:39:11.074076Z", "level": "INFO", "name": "pycti.connector", "message": "Message (delivery_tag=1) processed, thread terminated"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:40:29.130359Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-09T00:40:28.457Z"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:40:29.537468Z", "level": "INFO", "name": "pycti.connector", "message": "Importing the file http://opencti:8080/storage/get/import/pending/mustang_hashes.json"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:40:30.539360Z", "level": "ERROR", "name": "root", "message": "Error in message processing, reporting error to API", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py\", line 167, in _process_message\n    json_data[\"internal\"][\"work_id\"], message_task.result()\n  File \"/usr/local/lib/python3.10/concurrent/futures/thread.py\", line 58, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/opt/opencti-connector-import-file-stix/import-file-stix.py\", line 54, in _process_message\n    bundles_sent = self.helper.send_stix2_bundle(\n  File \"/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py\", line 874, in send_stix2_bundle\n    bundles = stix2_splitter.split_bundle(bundle, True, event_version)\n  File \"/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 74, in split_bundle\n    self.enlist_element(item[\"id\"], raw_data)\n  File \"/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 38, in enlist_element\n    nb_deps += self.enlist_element(value, raw_data)\n  File \"/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py\", line 19, in enlist_element\n    for key, value in item.items():\nRuntimeError: dictionary changed size during iteration"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:40:30.540003Z", "level": "INFO", "name": "pycti.api", "message": "Reporting work update_received work_72327164-0b35-482b-b5d6-a5a3f76b845f_2023-02-09T00:40:28.457Z"}
opencti-docker-connector-import-file-stix-1  | {"timestamp": "2023-02-09T00:40:30.831914Z", "level": "INFO", "name": "pycti.connector", "message": "Message (delivery_tag=2) processed, thread terminated"}
```

Looks like it expects `numpy` to be installed (logging into the connector reveals that it isn't, and it also isn't listed in `requirements.txt`)

Additionally, not entire sure what's going on with the `RuntimeError: dictionary changed size during iteration` but it sounds like a data structure that's being iterated across is also potentially being modified within a loop?

**Comment by ckane** [comment]
Dequoting the traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 167, in _process_message
    json_data["internal"]["work_id"], message_task.result()
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/opencti-connector-import-file-stix/import-file-stix.py", line 54, in _process_message
    bundles_sent = self.helper.send_stix2_bundle(
  File "/usr/local/lib/python3.10/site-packages/pycti/connector/opencti_connector_helper.py", line 874, in send_stix2_bundle
    bundles = stix2_splitter.split_bundle(bundle, True, event_version)
  File "/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py", line 74, in split_bundle
    self.enlist_element(item["id"], raw_data)
  File "/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py", line 38, in enlist_element
    nb_deps += self.enlist_element(value, raw_data)
  File "/usr/local/lib/python3.10/site-packages/pycti/utils/opencti_stix2_splitter.py", line 19, in enlist_element
    for key, value in item.items():
RuntimeError: dictionary changed size during iteration
```

**Comment by ckane** [comment]
Following https://github.com/OpenCTI-Platform/client-python/pull/330, I still get errors but the import at least gets to the point where it is stepping through all of the STIX entities. The next batch of errors is:
```
{'name': 'FunctionalError', 'message': 'Only stix-core-relationship can be created through this method.'}
```
```json
{"type": "bundle", "id": "bundle--1facc4ac-75f5-4539-8a23-f5f0da77ba9e", "spec_version": "2.1",
 "x_opencti_seq": 8, 
 "objects": [{"type": "relationship", "spec_version": "2.1", "id": "relationship--fff5db38-fa28-4f69-ab09-1e7b44052cb7",   
  "created_by_ref": "identity--acf55024-6bbe-486f-a27a-7967559324f4", "created": "2022-12-03T03:04:53.754701Z", 
  "modified": "2022-12-03T03:04:53.754701Z", "relationship_type": "pattern-contains",
  "source_ref": "indicator--1499f5df-fd75-4d4b-82e8-5d9d233852aa",
  "target_ref": "file--3cab879b-15d4-5e11-8636-4bc06a85e88d",
  "external_references": [{"source_name": "file2stix", "description": "This object was created using file2stix from the Signals Corps.", "url": "https://github.com/signalscorps/file2stix"}],
  "object_marking_refs": ["marking-definition--613f2e26-407d-48c7-9eca-b8e91df99dc9"],
  "nb_deps": 8}]}
```

**Comment by SamuelHassine** [comment]
Hello @ckane,

This relationship is not supported by OpenCTI and is not STIX compliant. But this is the same use case as "based-on" for us.

Any chance you can use based-on instead of pattern-contains?

Kind regards,
Samuel

**Comment by ckane** [comment]
`pattern-contains` doesn't appear in https://docs.oasis-open.org/cti/stix/v2.1/os/stix-v2.1-os.html#_p49j1fwoxldc so my conclusion is `file2stix` needs to be changed so it can be told to use relationships only present in the specification.
