### ISSUE TITLE
[URLScan] Connector errors out with: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by zendesk-gesparza** [OpenCTI-Platform/connectors#960]
## Description

Upon starting connector, it errors out with message `'NoneType' object has no attribute 'split'`. Running a raw curl request to the API shows that at times the results do not have the specified field.

## Environment

1. OS (where OpenCTI server runs): Docker
2. OpenCTI version: 5.4.1
3. OpenCTI client: Frontend
4. Other environment details: Running in AWS ECS

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Docker image within AWS ECS
2. Wait for ipv4 artifacts to skip
3. Error out

## Expected Output

Completely ingest

## Actual Output

```
2022-12-21T16:27:09.835-05:00	DEBUG:urlscan.connector:Skipping IPv4 observable: 154.213.21.207
2022-12-21T16:27:10.227-05:00	ERROR:urlscan.loop:Unhandled exception processing connector feed: 'NoneType' object has no attribute 'split'
2022-12-21T16:27:10.227-05:00	Traceback (most recent call last):
2022-12-21T16:27:10.227-05:00	File "/opt/connector/urlscan/loop.py", line 110, in _run_loop
2022-12-21T16:27:10.227-05:00	self._callback(work_id)
2022-12-21T16:27:10.227-05:00	File "/opt/connector/urlscan/connector.py", line 126, in _process_feed
2022-12-21T16:27:10.227-05:00	elif validators.ipv4(hostname):
2022-12-21T16:27:10.227-05:00	File "/opt/connector/.venv/lib/python3.10/site-packages/decorator.py", line 232, in fun
2022-12-21T16:27:10.227-05:00	return caller(func, *(extras + args), **kw)
2022-12-21T16:27:10.227-05:00	File "/opt/connector/.venv/lib/python3.10/site-packages/validators/utils.py", line 79, in wrapper
2022-12-21T16:27:10.227-05:00	value = func(*args, **kwargs)
2022-12-21T16:27:10.227-05:00	File "/opt/connector/.venv/lib/python3.10/site-packages/validators/ip_address.py", line 26, in ipv4
2022-12-21T16:27:10.227-05:00	groups = value.split(".")
2022-12-21T16:27:10.227-05:00	AttributeError: 'NoneType' object has no attribute 'split'
```

## Additional information

N/A

## Screenshots (optional)
N/A

**Comment by rlynch-ironnet** [comment]
This is due to URLs coming in with the format `blob:https://blahblahblah`
